/**
 * VERTICAL · Fisioterapia · Datos ficticios
 * Todos los datos son inventados para demo interna.
 * No representan personas, centros, sesiones, correos ni casos reales.
 * Ningún dato se envía a ningún sistema externo.
 */

export const MOCK_PACIENTES_FISIO = [
  {
    id: 'fp001',
    nombre: 'Laura Sanz Romero',
    email: 'laura.s@demo.ficticio',
    telefono: '600 000 011',
    centro: 'Centro Principal',
    servicio: 'Rehabilitación rodilla (LCA)',
    estado: 'sesion_agendada',
    estado_label: 'Sesión agendada',
    estado_color: 'green',
    valor_estimado: '370 €',
    origen: 'Derivación médica',
    prioridad: 'alta',
    prioridad_color: 'red',
    fecha_contacto: '11 ago 2026',
    proxima_accion: 'Sesión inicial postquirúrgica',
    sesiones_restantes: 9,
  },
  {
    id: 'fp002',
    nombre: 'Javier Morales Vega',
    email: 'javier.m@demo.ficticio',
    telefono: '600 000 012',
    centro: 'Centro Norte',
    servicio: 'Dolor lumbar crónico',
    estado: 'en_valoracion',
    estado_label: 'En valoración',
    estado_color: 'blue',
    valor_estimado: '200 €',
    origen: 'Google Ads',
    prioridad: 'media',
    prioridad_color: 'yellow',
    fecha_contacto: '13 ago 2026',
    proxima_accion: 'Enviar informe de valoración inicial',
    sesiones_restantes: null,
  },
  {
    id: 'fp003',
    nombre: 'Carmen López Ruiz',
    email: 'carmen.l@demo.ficticio',
    telefono: '600 000 013',
    centro: 'Centro Principal',
    servicio: 'Suelo pélvico postparto',
    estado: 'pendiente',
    estado_label: 'Pendiente confirmar',
    estado_color: 'yellow',
    valor_estimado: '200 €',
    origen: 'Instagram',
    prioridad: 'media',
    prioridad_color: 'yellow',
    fecha_contacto: '15 ago 2026',
    proxima_accion: 'Confirmar disponibilidad con Dra. López',
    sesiones_restantes: null,
  },
  {
    id: 'fp004',
    nombre: 'Pablo García Delgado',
    email: 'pablo.g@demo.ficticio',
    telefono: '600 000 014',
    centro: 'Servicio a domicilio',
    servicio: 'Primera valoración',
    estado: 'nuevo',
    estado_label: 'Nuevo lead',
    estado_color: 'indigo',
    valor_estimado: '–',
    origen: 'Web propia',
    prioridad: 'baja',
    prioridad_color: 'gray',
    fecha_contacto: '16 ago 2026',
    proxima_accion: 'Agendar valoración inicial gratuita',
    sesiones_restantes: null,
  },
  {
    id: 'fp005',
    nombre: 'Elena Martínez Blanco',
    email: 'elena.m@demo.ficticio',
    telefono: '600 000 015',
    centro: 'Centro Principal',
    servicio: 'Rehabilitación deportiva (hombro)',
    estado: 'perdido',
    estado_label: 'Perdido',
    estado_color: 'red',
    valor_estimado: '200 €',
    origen: 'Referido',
    prioridad: 'baja',
    prioridad_color: 'gray',
    fecha_contacto: '09 ago 2026',
    proxima_accion: 'Activar secuencia de recuperación',
    sesiones_restantes: null,
  },
];

export const MOCK_METRICAS_FISIO = {
  consultas_mes: 38,
  precalificadas_pct: 71,
  con_cita_pct: 47,
  oportunidades_recuperadas: 6,
  valor_pipeline: '18.200 €',
  tasa_conversion_primera_valoracion: 62,
  por_origen: [
    { origen: 'Derivación médica', pct: 35 },
    { origen: 'Web propia',        pct: 28 },
    { origen: 'Google Ads',        pct: 21 },
    { origen: 'Instagram',         pct: 16 },
  ],
  por_servicio: [
    { servicio: 'Lumbalgia / espalda',     pct: 30 },
    { servicio: 'Deporte / rehab.',        pct: 27 },
    { servicio: 'Primera valoración',      pct: 20 },
    { servicio: 'Postoperatorio',          pct: 14 },
    { servicio: 'Suelo pélvico',           pct: 9  },
  ],
  por_centro: [
    { centro: 'Centro Principal',      pct: 52 },
    { centro: 'Centro Norte',          pct: 32 },
    { centro: 'Servicio a domicilio',  pct: 16 },
  ],
};

export const MOCK_LEADS_ABANDONO_FISIO = [
  {
    id: 'fla001',
    nombre: 'Usuario anónimo #7201 (ficticio)',
    servicio: 'Bono 5 sesiones — Lumbalgia',
    paso_abandono: 'Selección de profesional — no completó la reserva',
    fecha: '19 ago 2026',
    estado_recuperacion: 'en_proceso',
    secuencia: [
      { paso: 1, tipo: 'Notificación', asunto: 'Tu sesión sigue disponible',             delay: 'Inmediato', estado: 'simulado' },
      { paso: 2, tipo: 'Email',        asunto: 'Hemos guardado tu consulta (ficticio)',   delay: '12 h',      estado: 'simulado' },
      { paso: 3, tipo: 'Recordatorio', asunto: 'Primera valoración gratuita esta semana', delay: '3 días',    estado: 'pendiente' },
    ],
  },
  {
    id: 'fla002',
    nombre: 'Usuario anónimo #5503 (ficticio)',
    servicio: 'Primera valoración gratuita',
    paso_abandono: 'Selección de franja horaria — abandonó antes de confirmar',
    fecha: '22 ago 2026',
    estado_recuperacion: 'recuperado',
    secuencia: [
      { paso: 1, tipo: 'Notificación', asunto: '¿Necesitas ayuda para elegir horario?',  delay: 'Inmediato', estado: 'simulado' },
      { paso: 2, tipo: 'Email',        asunto: 'Tu valoración sin coste te espera',       delay: '24 h',      estado: 'simulado' },
      { paso: 3, tipo: 'Seguimiento',  asunto: 'Seguimiento del equipo (simulado)',       delay: '5 días',    estado: 'simulado' },
    ],
  },
  {
    id: 'fla003',
    nombre: 'Usuario anónimo #8812 (ficticio)',
    servicio: 'Bono 10 sesiones — Rehabilitación deportiva',
    paso_abandono: 'Visualizó tarifas pero no solicitó cita',
    fecha: '24 ago 2026',
    estado_recuperacion: 'en_proceso',
    secuencia: [
      { paso: 1, tipo: 'Email',        asunto: 'Compara nuestros bonos (ficticio)',       delay: 'Inmediato', estado: 'simulado' },
      { paso: 2, tipo: 'Oferta',       asunto: 'Sesión de prueba gratuita (ficticio)',    delay: '48 h',      estado: 'pendiente' },
    ],
  },
];

export const MOCK_SLOTS_FISIO = [
  { id: 'fsl001', fecha: 'Mañana, 29 ago', hora: '09:30', centro: 'Centro Principal',     profesional: 'Dr. Martínez (ficticio)',  disponible: true },
  { id: 'fsl002', fecha: 'Mañana, 29 ago', hora: '11:00', centro: 'Centro Norte',          profesional: 'Dra. García (ficticia)',   disponible: true },
  { id: 'fsl003', fecha: 'Dom, 30 ago',    hora: '10:00', centro: 'Centro Principal',     profesional: 'Dra. García (ficticia)',   disponible: true },
];
