// Agent Evaluation Registry — ADV-10

export const AGENT_EVALUATION_REGISTRY = Object.freeze({
  name: 'agent-evaluation',
  version: '1.0.0',
  description: 'Reusable agent evaluation + Langfuse tracing foundation',
  modules: Object.freeze([
    'evaluationDefinition',
    'evaluationDimensions',
    'evaluationResult',
    'evaluationDataset',
    'evaluationRunner',
    'evaluationReport',
    'evaluationDashboard',
    'criticalFailurePolicy',
    'humanlikeEvaluator',
    'brevityEvaluator',
    'toneMatchEvaluator',
    'businessFitEvaluator',
    'groundingEvaluator',
    'toolUseEvaluator',
    'memoryEvaluator',
    'escalationEvaluator',
    'safetyEvaluator',
    'ethicalSalesEvaluator',
    'multiTurnEvaluator',
    'salesEvaluator',
    'supportEvaluator',
    'bookingEvaluator',
    'leadAgentEvaluator',
    'crmAgentEvaluator',
    'costEvaluator',
    'latencyEvaluator',
    'qualityCostAnalyzer',
    'regressionSuite',
    'agentBaseline',
    'agentQualityScore',
    'agentQualityGate',
    'fastEvalMode',
    'finalEvalMode',
    'promptVersion',
    'promptPromotion',
    'modelComparison',
    'telemetryProvider',
    'langfuseAdapter',
    'agentTrace',
    'langfuseDashboardBridge',
    'redactionPolicy',
    'samplingPolicy',
    'privacyPolicy',
    'retentionPolicy',
    'bridges/cicdBridge',
    'bridges/observabilityBridge',
    'bridges/agentEngineBridge',
    'bridges/leadEngineBridge',
    'bridges/crmBridge',
    'fixtures/goodFixtures',
    'fixtures/failureFixtures',
    'fixtures/multiTurnFixtures',
    'fixtures/goldenDataset',
    // ADV-10b
    'businessFactGroundingEvaluator',
    'availabilityGroundingEvaluator',
    'businessTruthQualityGate',
    'pricingFactEvaluator',
    'facilityFactEvaluator',
    'serviceFactEvaluator',
    'businessPolicyEvaluator',
    'business-truth/businessSourceOfTruth',
    'business-truth/businessTruthSourcePriority',
    'business-truth/businessFact',
    'business-truth/unknownBusinessFactPolicy',
    'business-truth/businessFactFreshnessPolicy',
    'business-truth/businessFactResolver',
    'business-truth/businessTruthConflictResolver',
    'business-truth/businessFactConsistencyEngine',
    'business-truth/businessScheduleProvider',
    'business-truth/businessAvailabilityResolver',
    'business-truth/bookingAgentGrounding',
    'business-truth/agentBusinessFactPolicy',
    'business-truth/clientBusinessOverride',
    'business-truth/clientFactIsolation',
    'business-truth/cp04CompatAdapter',
    'business-truth/factoryGenerationBridge',
    'business-truth/approvedFactIngestion',
    'business-truth/businessAppConfigProvider',
    'business-truth/businessDataProvider',
    'business-truth/businessOperationalApiProvider',
  ]),
  stats: Object.freeze({
    totalModules: 82,
    bridges: 5,
    fixtures: 4,
    goldenDatasetCases: 65,
    multiTurnCases: 10,
    evaluatorDimensions: 19,
    criticalFailureTypes: 17,
    agentTypes: 7,
    promptStatuses: 4,
    samplingModes: 5,
    privacyLevels: 4,
    retentionTiers: 5,
    businessTruthModules: 19,
    businessFactCategories: 19,
    sourcePriorityLevels: 9,
  }),
  langfuseIntegration: 'dry-run-only',
  isReal: false,
});
