// Agent Engine Registry — ADV-03

export const AGENT_ENGINE_REGISTRY = Object.freeze({
  id:          'agent-engine',
  version:     '1.0.0',
  description: 'Factory Agent Engine — generates AI agents adapted to sector/business/client/channel.',
  modules: Object.freeze([
    'agentDefinition',
    'humanProfile',
    'responseLengthEngine',
    'toneEngine',
    'purposeEngine',
    'salesPolicy',
    'psychologyPolicy',
    'objectionEngine',
    'nextBestAction',
    'trustPolicy',
    'knowledgeProfile',
    'memoryPolicy',
    'toolPolicy',
    'escalationEngine',
    'channelProfiles',
    'agentArchetypes',
    'verticalAdapters',
    'clientOverrides',
    'agentGenerator',
    'promptContract',
    'conversationStages',
    'intentModel',
    'responsePlanner',
    'leadQualification',
    'voiceFoundation',
    'aiRouterIntegration',
    'observabilityIntegration',
    'cicdIntegration',
    'evaluationModel',
    'antiParagraphGate',
    'humannessQA',
    'verticalSafety',
    'agentFixtures',
  ]),
  agentTypes:    Object.freeze(['CHAT', 'SALES', 'SUPPORT', 'BOOKING', 'LEAD', 'VOICE']),
  verticals:     Object.freeze(['dental', 'physio', 'psychology', 'speech_therapy', 'sports', 'padel', 'veterinary', 'hairdresser', 'beauty', 'legal', 'fertility', 'education', 'DEFAULT']),
  channels:      Object.freeze(['WEB_CHAT', 'WHATSAPP', 'EMAIL', 'SOCIAL_DM', 'VOICE']),
  principles: Object.freeze([
    'CONSULTATIVE_SELLING',
    'HONEST_AND_HUMBLE',
    'LEAST_PRIVILEGE',
    'EASY_EXIT',
    'NO_DARK_PATTERNS',
    'ALWAYS_AVAILABLE_ESCALATION',
  ]),
  isReal:   false,
  dataType: 'REGISTRY_MODULE',
});
