// Agent Evaluation Registry — ADV-10

export const AGENT_EVALUATION_REGISTRY = Object.freeze({
  name: 'agent-evaluation',
  version: '1.0.0',
  description: 'Reusable agent evaluation + Langfuse tracing foundation',
  modules: Object.freeze([
    'evaluationDefinition',
    'evaluationDimensions',
    'evaluationResult',
    'evaluationDataset',
    'evaluationRunner',
    'evaluationReport',
    'evaluationDashboard',
    'criticalFailurePolicy',
    'humanlikeEvaluator',
    'brevityEvaluator',
    'toneMatchEvaluator',
    'businessFitEvaluator',
    'groundingEvaluator',
    'toolUseEvaluator',
    'memoryEvaluator',
    'escalationEvaluator',
    'safetyEvaluator',
    'ethicalSalesEvaluator',
    'multiTurnEvaluator',
    'salesEvaluator',
    'supportEvaluator',
    'bookingEvaluator',
    'leadAgentEvaluator',
    'crmAgentEvaluator',
    'costEvaluator',
    'latencyEvaluator',
    'qualityCostAnalyzer',
    'regressionSuite',
    'agentBaseline',
    'agentQualityScore',
    'agentQualityGate',
    'fastEvalMode',
    'finalEvalMode',
    'promptVersion',
    'promptPromotion',
    'modelComparison',
    'telemetryProvider',
    'langfuseAdapter',
    'agentTrace',
    'langfuseDashboardBridge',
    'redactionPolicy',
    'samplingPolicy',
    'privacyPolicy',
    'retentionPolicy',
    'bridges/cicdBridge',
    'bridges/observabilityBridge',
    'bridges/agentEngineBridge',
    'bridges/leadEngineBridge',
    'bridges/crmBridge',
    'fixtures/goodFixtures',
    'fixtures/failureFixtures',
    'fixtures/multiTurnFixtures',
    'fixtures/goldenDataset',
  ]),
  stats: Object.freeze({
    totalModules: 53,
    bridges: 5,
    fixtures: 4,
    goldenDatasetCases: 60,
    multiTurnCases: 10,
    evaluatorDimensions: 16,
    criticalFailureTypes: 10,
    agentTypes: 7,
    promptStatuses: 4,
    samplingModes: 5,
    privacyLevels: 4,
    retentionTiers: 5,
  }),
  langfuseIntegration: 'dry-run-only',
  isReal: false,
});
