// AI Media Registry Entry — ADV-13

export const AI_MEDIA_REGISTRY = Object.freeze({
  version:      '1.0.0',
  adv:          'ADV-13',
  name:         'AI Media Engine V1 — Avatar + Voice + Video IA',
  totalModules: 53,
  guardrails: Object.freeze({
    FACTORY_AGENCY_SCOPE_ONLY:  'SI',
    NO_REAL_SOCIAL_PUBLISH:     'SI',
    NO_REAL_AD_SPEND:           'SI',
    NO_REAL_EXTERNAL_COST:      'SI',
    NO_REAL_PERSONAL_MEDIA:     'SI',
    NO_REAL_AVATAR_PROVIDER:    'SI',
    NO_REAL_LIPSYNC:            'SI',
    NO_REAL_SECRETS:            'SI',
  }),
  bridges: Object.freeze([
    'ADV-01 Observabilidad',
    'ADV-03 Agent Engine',
    'ADV-07 Premium Experience',
    'ADV-10 Langfuse',
    'ADV-11 Voice Agent',
    'ADV-12 MCP Layer',
  ]),
  modules: Object.freeze([
    'aiMediaProject', 'mediaObjective', 'avatarProfile',
    'mediaIdentityConsent', 'mediaVoiceProfile', 'spanishVoiceProfiles',
    'mediaScriptEngine', 'mediaClaimPolicy', 'mediaScriptLengthPolicy',
    'mediaChannelProfile', 'mediaFormatResolver', 'mediaSafeAreaPolicy',
    'mediaStoryboard', 'mediaVisualStyle', 'mediaBrandBridge',
    'avatarVideoProvider', 'mediaTTSBridge', 'lipSyncProvider', 'videoCompositionPlan',
    'mediaRightsPolicy', 'mediaCostGuard', 'mediaCostEstimate',
    'mediaProviderRouter', 'mediaHumanApprovalPolicy',
    'socialPublishPlan', 'mediaAutomationManifest', 'mediaContentCalendar',
    'mediaVariantsEngine', 'mediaExperiment',
    'captionEngine', 'subtitlePlan',
    'mediaHookEvaluator', 'mediaCtaEvaluator', 'mediaScriptEvaluator',
    'mediaVoiceQualityEvaluator', 'lipSyncQualityEvaluator',
    'avatarQualityEvaluator', 'mediaQualityScore', 'mediaQualityGate',
    'mediaAccessibilityPolicy', 'mediaPerformanceProfile',
    'mediaLandingBridge', 'mediaAgentBridge', 'mediaVoiceAgentBridge',
    'mediaMCPBridge', 'mediaObservabilityBridge', 'mediaLangfuseBridge',
    'mediaPrivacyPolicy', 'mediaRetentionPolicy', 'mediaProvenance',
    'syntheticMediaDisclosurePolicy',
    'mediaOutputPackage', 'thumbnailPlan',
  ]),
  fixtures: Object.freeze([
    'fixtureBusinesses', 'fixtureMediaProjects', 'goodFixtures', 'failureFixtures',
  ]),
  isReal: false,
});
