// Factory Registry — Backup + Restore + Disaster Recovery (ADV-18)

export const BACKUP_RESTORE_REGISTRY = Object.freeze({
  name:    'Backup Engine + Restore Validation + Disaster Recovery Foundation',
  version: '1.0.0',
  adv:     'ADV-18',
  status:  '100_PERCENT',

  modules: Object.freeze([
    'backups/scope/backupScope.js',
    'backups/policy/backupPolicy.js',
    'backups/policy/backupRetentionPolicy.js',
    'backups/policy/backupVersionPolicy.js',
    'backups/policy/backupEncryptionPolicy.js',
    'backups/policy/backupKeyReferencePolicy.js',
    'backups/policy/backupCompressionPolicy.js',
    'backups/policy/backupDeduplicationPolicy.js',
    'backups/policy/backupStorageProfile.js',
    'backups/policy/backupPIIPolicy.js',
    'backups/policy/backupSecretExclusionPolicy.js',
    'backups/policy/backupHumanApprovalPolicy.js',
    'backups/job/backupJob.js',
    'backups/job/backupSchedule.js',
    'backups/job/backupExpiryEvaluator.js',
    'backups/manifest/backupItem.js',
    'backups/manifest/backupManifest.js',
    'backups/manifest/backupIntegrityChecksum.js',
    'backups/integrity/validateBackupIntegrity.js',
    'backups/quality/backupQualityScore.js',
    'backups/quality/backupQualityGate.js',
    'backups/restore/restorePoint.js',
    'backups/restore/restorePlan.js',
    'backups/restore/partialRestorePlan.js',
    'backups/restore/fullRestorePlan.js',
    'backups/restore/simulateRestore.js',
    'backups/restore/validateRestorePlan.js',
    'backups/restore/restoreConflictDetector.js',
    'backups/restore/restoreConflictPolicy.js',
    'backups/restore/preRestoreSafetyPolicy.js',
    'backups/restore/restoreRollbackPlan.js',
    'backups/restore/restoreTestPolicy.js',
    'backups/recovery/disasterRecoveryProfile.js',
    'backups/recovery/recoveryObjectivePolicy.js',
    'backups/recovery/recoveryDrill.js',
    'backups/recovery/recoveryReadinessScore.js',
    'backups/recovery/recoveryQualityGate.js',
    'backups/catalog/backupCatalog.js',
    'backups/catalog/restoreCatalog.js',
    'backups/audit/backupAuditEntry.js',
    'backups/bridges/observabilityBridge.js',
    'backups/bridges/healthBridge.js',
    'backups/bridges/cicdBridge.js',
    'backups/bridges/productionPipelineBridge.js',
    'backups/bridges/dockerEnvBridge.js',
    'backups/bridges/mcpBridge.js',
    'backups/bridges/multiagentBridge.js',
    'backups/fixtures/backupFixtures.js',
    'backups/fixtures/restoreFixtures.js',
    'backups/fixtures/failureFixtures.js',
    'backups/fixtures/multiTenantFixtures.js',
    'backups/fixtures/recoveryDrillFixtures.js',
    'backups/index.js',
  ]),

  guardrails: Object.freeze({
    NO_REAL_BACKUP:              true,
    NO_REAL_RESTORE:             true,
    NO_REAL_DELETE:              true,
    NO_REAL_EXTERNAL_COST:       true,
    SECRET_EXCLUSION_ENFORCED:   true,
    CLIENT_ISOLATION_ENFORCED:   true,
    REAL_RESTORE_REQUIRES_HUMAN: true,
  }),

  keyCapabilities: Object.freeze([
    'BackupScope — 12 scope types',
    'BackupPolicy — frequency/retention/encryption/integrity/isolation',
    'BackupJob — 7 states (PLANNED→COMPLETED/FAILED/BLOCKED/EXPIRED)',
    'BackupManifest — versioned + checksums + dependencies',
    'BackupItem — 12 types + sensitivity + encryption flags',
    'SecretExclusionPolicy — 12 patterns, triggers BLOCKED',
    'PII Policy — 5 levels + minimization + restore approval',
    'VersionPolicy — FULL/INCREMENTAL_FOUNDATION/SNAPSHOT/CONFIG_ONLY',
    'IntegrityChecksum — SHA-256 abstraction, verify()',
    'validateBackupIntegrity — 8 failure conditions + BLOCKED/CORRUPTED/DEGRADED/VALID',
    'BackupQualityScore — 8 weighted factors',
    'BackupQualityGate — 8 BLOCKED reasons',
    'RestorePoint — 5 states (AVAILABLE→VERIFIED/DEGRADED/INCOMPATIBLE/BLOCKED)',
    'RestorePlan — DRY_RUN/PARTIAL/FULL modes (ADV-18: DRY_RUN only)',
    'PartialRestorePlan — 7 selectable scopes',
    'FullRestorePlan — 7-step lifecycle',
    'simulateRestore — wouldRestore/wouldSkip/wouldBlock/estimatedRisk',
    'validateRestorePlan — 6 failure conditions',
    'RestoreConflictDetector — 6 conflict types',
    'RestoreConflictPolicy — BLOCK/SKIP/REQUIRE_HUMAN/MERGE_FOUNDATION',
    'PreRestoreSafetyPolicy — snapshot required before real restore',
    'RestoreRollbackPlan — 6-step rollback lifecycle',
    'RestoreTestPolicy — integrity + dry-run both required',
    'DisasterRecoveryProfile — LOW/STANDARD/HIGH/CRITICAL criticality',
    'RecoveryObjectivePolicy — qualitative RPO/RTO',
    'RecoveryDrill — PLANNED/PASSED/WARNING/FAILED',
    'RecoveryReadinessScore — 8 weighted factors',
    'RecoveryQualityGate — 6 BLOCKED reasons',
    'BackupCatalog — per-client, client-isolated',
    'RestoreCatalog — links restore points to backups',
    'BackupAuditEntry — 11 action types',
    '7 bridges — Observability/Health/CICD/Production/Docker/MCP/MultiAgent',
    '5 fixture sets — backup/restore/failure/multi-tenant/recovery-drill',
    'Client isolation — cross-client access always BLOCKED',
    'Human approval policy — 7 triggers requiring approval',
  ]),
});
