/**
 * Factory Registry — Component Registry V2
 * Metadata-driven component catalog. Each entry describes purpose, verticals,
 * audiences, motion cost, performance cost, and V2 tags.
 */

export const COMPONENT_REGISTRY = Object.freeze([
  // ─── Motion Foundation ─────────────────────────────────────────────────────
  {
    id: 'FactoryMotion',
    category: 'motion',
    purpose: 'Generic motion wrapper — applies enter/exit transitions via motion/react',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['prefers-reduced-motion'],
    tags: ['wrapper', 'animation', 'foundation'],
  },
  {
    id: 'MotionButton',
    category: 'motion',
    purpose: 'Button with hover scale + tap feedback via spring animation',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['keyboard-nav', 'focus-ring'],
    tags: ['button', 'interaction', 'cta'],
  },
  {
    id: 'MotionCard',
    category: 'motion',
    purpose: 'Card with spring hover elevation and shadow',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: [],
    tags: ['card', 'hover', 'elevation'],
  },
  {
    id: 'Reveal',
    category: 'motion',
    purpose: 'Scroll-triggered entrance animation (fade + direction)',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'low',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['prefers-reduced-motion'],
    tags: ['scroll', 'entrance', 'visibility'],
  },
  {
    id: 'Stagger',
    category: 'motion',
    purpose: 'Staggered list entrance — children appear sequentially',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'medium',
    performanceCost: 'low',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['prefers-reduced-motion'],
    tags: ['list', 'stagger', 'sequence'],
  },
  {
    id: 'AnimatedMetric',
    category: 'motion',
    purpose: 'Animated counter that counts up to a numeric value on scroll',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'low',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['prefers-reduced-motion'],
    tags: ['counter', 'metric', 'hero', 'social-proof'],
  },
  {
    id: 'PageTransition',
    category: 'motion',
    purpose: 'Route-level fade/slide transition wrapper',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'low',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['prefers-reduced-motion'],
    tags: ['navigation', 'page', 'transition'],
  },
  {
    id: 'LayoutTransition',
    category: 'motion',
    purpose: 'Smooth layout change using motion layout prop',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'medium',
    performanceCost: 'medium',
    v2: true,
    requiresLib: 'motion/react',
    a11y: [],
    tags: ['layout', 'reflow', 'list'],
  },
  {
    id: 'MotionProgress',
    category: 'motion',
    purpose: 'Animated progress bar with smooth width transition',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['progressbar', 'aria-valuenow'],
    tags: ['progress', 'bar', 'metric'],
  },
  {
    id: 'MotionTabs',
    category: 'motion',
    purpose: 'Tabs with shared animated underline indicator',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['tablist', 'tab', 'aria-selected'],
    tags: ['tabs', 'navigation', 'indicator'],
  },
  {
    id: 'MotionDrawer',
    category: 'motion',
    purpose: 'Side panel with spring slide-in animation and overlay',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'medium',
    performanceCost: 'low',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['dialog', 'aria-modal', 'focus-trap', 'escape-key'],
    tags: ['drawer', 'panel', 'overlay'],
  },
  {
    id: 'MotionToast',
    category: 'motion',
    purpose: 'Animated toast notifications with enter/exit',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'low',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: 'motion/react',
    a11y: ['alert', 'aria-live'],
    tags: ['toast', 'notification', 'feedback'],
  },
  // ─── Primitives ────────────────────────────────────────────────────────────
  {
    id: 'Drawer',
    category: 'primitive',
    purpose: 'Headless accessible drawer without animation library',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['dialog', 'aria-modal', 'focus-trap', 'escape-key'],
    tags: ['drawer', 'headless', 'accessible'],
  },
  {
    id: 'Dialog',
    category: 'primitive',
    purpose: 'Modal dialog with focus trap and accessible semantics',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['dialog', 'aria-modal', 'focus-trap', 'escape-key'],
    tags: ['modal', 'dialog', 'headless'],
  },
  {
    id: 'Popover',
    category: 'primitive',
    purpose: 'Positioned overlay triggered by a reference element',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['dialog', 'aria-expanded', 'escape-key'],
    tags: ['popover', 'overlay', 'positioned'],
  },
  {
    id: 'Tooltip',
    category: 'primitive',
    purpose: 'Hover/focus tooltip with delay and positioning',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['tooltip', 'aria-describedby'],
    tags: ['tooltip', 'hint', 'accessible'],
  },
  {
    id: 'NavigationMenu',
    category: 'primitive',
    purpose: 'Horizontal/vertical nav with optional dropdown children',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['nav', 'aria-expanded', 'aria-haspopup'],
    tags: ['nav', 'menu', 'dropdown'],
  },
  {
    id: 'Combobox',
    category: 'primitive',
    purpose: 'Searchable select dropdown with listbox semantics',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['listbox', 'option', 'aria-selected', 'aria-expanded'],
    tags: ['select', 'combobox', 'search'],
  },
  {
    id: 'Autocomplete',
    category: 'primitive',
    purpose: 'Type-ahead input with filtered option list',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: ['listbox', 'aria-autocomplete', 'keyboard-nav'],
    tags: ['autocomplete', 'search', 'input'],
  },
  {
    id: 'ScrollArea',
    category: 'primitive',
    purpose: 'Overflow scroll container with custom scrollbar styling',
    verticals: ['*'],
    audiences: ['*'],
    motionCost: 'none',
    performanceCost: 'negligible',
    v2: true,
    requiresLib: null,
    a11y: [],
    tags: ['scroll', 'overflow', 'container'],
  },
]);

export function getComponentById(id) {
  return COMPONENT_REGISTRY.find(c => c.id === id) ?? null;
}

export function getComponentsByCategory(category) {
  return COMPONENT_REGISTRY.filter(c => c.category === category);
}

export function getComponentsByTag(tag) {
  return COMPONENT_REGISTRY.filter(c => c.tags.includes(tag));
}
