// Agency CRM Registry Entry — ADV-09

export const CRM_REGISTRY = Object.freeze({
  name:        'agency-crm',
  version:     '1.0.0',
  paso:        'ADV-09',
  description: 'Reusable commercial CRM engine: lead→opportunity→pipeline→proposal→won/lost→handoff',
  modules: Object.freeze([
    'salesPipeline',
    'crmLead',
    'crmOpportunity',
    'crmAccount',
    'crmContact',
    'crmActivity',
    'crmTask',
    'crmDeal',
    'stageTransitionPolicy',
    'nextActionEngine',
    'staleDetector',
    'followUpPolicy',
    'crmQualification',
    'discoveryContext',
    'proposalContext',
    'dealValueEstimate',
    'pipelineForecast',
    'dealOutcome',
    'lostDealAnalysis',
    'wonDealHandoff',
    'crmPriority',
    'crmHealthScore',
    'pipelineHealthReport',
    'kanbanViewModel',
    'dashboardModel',
    'agencyCRMReport',
    'crmQualityScore',
    'crmPrivacyPolicy',
    'crmRetentionPolicy',
    'crmIdempotencyPolicy',
    'leadBridge',
    'bridges/agentEngineBridge',
    'bridges/premiumExperienceBridge',
    'bridges/makeBridge',
    'bridges/observabilityBridge',
  ]),
  fixtureLeads:  40,
  crmStages:     12,
  isReal: false,
});

export const CRM_REGISTRY_VERSION = '1.0.0';
