// Factory Registry — Security + Privacy + GDPR + CMP (ADV-19)

export const SECURITY_PRIVACY_REGISTRY = Object.freeze({
  name:    'Security Engine + Privacy by Design + Consent Foundation + GDPR Technical Readiness',
  version: '1.0.0',
  adv:     'ADV-19',
  status:  '100_PERCENT',

  modules: Object.freeze([
    'security/posture/securityPostureProfile.js',
    'security/posture/securityRisk.js',
    'security/posture/securityBaselinePolicy.js',
    'security/data/dataClassificationPolicy.js',
    'security/data/piiDataInventory.js',
    'security/data/dataPurposePolicy.js',
    'security/data/dataMinimizationPolicy.js',
    'security/privacy/privacyRetentionPolicy.js',
    'security/privacy/dataDeletionPlan.js',
    'security/privacy/anonymizationPolicy.js',
    'security/privacy/pseudonymizationPolicy.js',
    'security/gdpr/gdprDataSubjectRight.js',
    'security/gdpr/dataSubjectRequest.js',
    'security/gdpr/dsarIdentityVerificationPolicy.js',
    'security/gdpr/dsarDataMap.js',
    'security/gdpr/gdprResponsePlan.js',
    'security/gdpr/legalBasisProfile.js',
    'security/consent/consentRecord.js',
    'security/consent/consentPolicy.js',
    'security/consent/consentManagementPlatformFoundation.js',
    'security/consent/cookieCategory.js',
    'security/consent/trackerDefinition.js',
    'security/consent/defaultConsentPolicy.js',
    'security/consent/consentWithdrawalPolicy.js',
    'security/consent/consentPolicyVersion.js',
    'security/consent/cookieBannerModel.js',
    'security/consent/privacyPreferenceCenterModel.js',
    'security/headers/securityHeadersPolicy.js',
    'security/headers/contentSecurityPolicyBuilder.js',
    'security/auth/authenticationSecurityPolicy.js',
    'security/auth/sessionSecurityPolicy.js',
    'security/auth/authorizationPolicyEvaluator.js',
    'security/auth/objectAccessControlPolicy.js',
    'security/io/inputSecurityPolicy.js',
    'security/io/outputSecurityPolicy.js',
    'security/secrets/secretManagementPolicy.js',
    'security/secrets/secretLeakDetection.js',
    'security/secrets/privacyLoggingPolicy.js',
    'security/audit/securityAuditEntry.js',
    'security/incidents/securityIncident.js',
    'security/incidents/securityIncidentResponsePlan.js',
    'security/incidents/personalDataBreachAssessment.js',
    'security/third-party/dependencySecurityPolicy.js',
    'security/third-party/thirdPartyProcessorProfile.js',
    'security/third-party/internationalDataTransferProfile.js',
    'security/ai/aiPrivacyPolicy.js',
    'security/ai/aiProviderDataHandlingProfile.js',
    'security/agents/agentSecurityPolicy.js',
    'security/agents/promptInjectionSecurityPolicy.js',
    'security/agents/toolSecurityPolicy.js',
    'security/api/webhookSecurityPolicy.js',
    'security/api/apiSecurityPolicy.js',
    'security/api/rateLimitPolicy.js',
    'security/api/abuseDetectionPolicy.js',
    'security/api/fileUploadSecurityPolicy.js',
    'security/isolation/securityClientIsolationEvaluator.js',
    'security/isolation/tenantSecurityContext.js',
    'security/isolation/privilegeEscalationDetector.js',
    'security/quality/securityQualityScore.js',
    'security/quality/privacyQualityScore.js',
    'security/quality/gdprTechnicalReadinessScore.js',
    'security/quality/cmpReadinessScore.js',
    'security/quality/securityQualityGate.js',
    'security/quality/privacyQualityGate.js',
    'security/quality/gdprTechnicalReadinessGate.js',
    'security/quality/cmpQualityGate.js',
    'security/bridges/observabilityBridge.js',
    'security/bridges/cicdBridge.js',
    'security/bridges/productionPipelineBridge.js',
    'security/bridges/dockerBridge.js',
    'security/bridges/backupBridge.js',
    'security/bridges/browserQABridge.js',
    'security/bridges/healthBridge.js',
    'security/fixtures/securityFixtures.js',
    'security/fixtures/privacyFixtures.js',
    'security/fixtures/cmpFixtures.js',
    'security/fixtures/gdprFixtures.js',
    'security/fixtures/attackFixtures.js',
    'security/fixtures/failureFixtures.js',
    'security/index.js',
  ]),

  guardrails: Object.freeze({
    NO_REAL_DATA_DELETE:       true,
    NO_REAL_SECRET_ROTATION:   true,
    NO_REAL_TRACKING:          true,
    NO_REAL_CONSENT_CAPTURE:   true,
    NO_REAL_EXTERNAL_COST:     true,
    SECRET_EXCLUSION_ENFORCED: true,
    CLIENT_ISOLATION_ENFORCED: true,
    LEGAL_CERTIFICATION:       false,
  }),

  keyCapabilities: Object.freeze([
    'SecurityPostureProfile — 5 statuses (UNKNOWN/BASELINE/HARDENED/DEGRADED/BLOCKED)',
    'SecurityRisk — 13 categories, 5 severities, risk scoring',
    'SecurityBaselinePolicy — 12 controls, 6 required',
    'DataClassificationPolicy — 6 classes, auto-classifier',
    'PIIDataInventory — 10 PII types, 5 legal bases',
    'DataPurposePolicy — allowed/forbidden uses, no silent reuse',
    'DataMinimizationPolicy — unnecessary PII detection',
    'PrivacyRetentionPolicy — 5 presets + LEGAL_HOLD',
    'DataDeletionPlan — DRY_RUN only in ADV-19',
    'AnonymizationPolicy — direct/quasi-identifier classification',
    'PseudonymizationPolicy — no key material stored',
    'GDPR Rights — 6 rights, deadline tracking',
    'DataSubjectRequest — 6 states, identity verification required',
    'DSARIdentityVerificationPolicy — email alone insufficient',
    'DSARDataMap — 10 data sources',
    'GDPRResponsePlan — 8-step lifecycle, simulation only',
    'LegalBasisProfile — 7 bases, UNKNOWN→legal review',
    'ConsentRecord — GRANTED/DENIED/WITHDRAWN/EXPIRED/UNKNOWN',
    'ConsentPolicy — dark pattern detection (5 patterns)',
    'CMP Foundation — categories/vendors/purposes/region',
    'CookieCategory — STRICTLY_NECESSARY/PREFERENCES/ANALYTICS/MARKETING/UNKNOWN',
    'TrackerDefinition — UNKNOWN always BLOCKED',
    'DefaultConsentPolicy — non-essential OFF before consent',
    'ConsentWithdrawalPolicy — as accessible as grant',
    'ConsentPolicyVersion — material change → new consent',
    'CookieBannerModel — ACCEPT+REJECT+CONFIGURE required',
    'SecurityHeadersPolicy — 8 headers evaluated',
    'CSP Builder — no unsafe-eval without justification',
    'AuthenticationSecurityPolicy — 7 controls',
    'SessionSecurityPolicy — expiry/idle/rotation/same-site',
    'AuthorizationPolicyEvaluator — deny by default',
    'ObjectAccessControlPolicy — IDOR protection',
    'InputSecurityPolicy — XSS/SQLi/path-traversal/template injection',
    'OutputSecurityPolicy — secret/PII/unsafe-HTML detection',
    'SecretManagementPolicy — reference only, no key material',
    'SecretLeakDetection — 10 patterns (ADV-02 extended)',
    'PrivacyLoggingPolicy — never log secrets/PII/payments',
    'SecurityAuditEntry — 12 actions, no secrets in log',
    'SecurityIncident — 6 states, severity lifecycle',
    'IncidentResponsePlan — 7 steps',
    'PersonalDataBreachAssessment — LEGAL_REVIEW_REQUIRED when warranted',
    'DependencySecurityPolicy — lockfile/vuln/deprecated/supply-chain',
    'ThirdPartyProcessorProfile — DPA status tracking',
    'InternationalDataTransferProfile — EU_EEA/adequacy/SCC/BLOCKED',
    'AIPrivacyPolicy — prompt PII, context minimization (ADV-16)',
    'AIProviderDataHandlingProfile — UNKNOWN≠safe',
    'AgentSecurityPolicy — no self-grant, no cross-client (ADV-17)',
    'PromptInjectionSecurityPolicy — 8 injection patterns',
    'ToolSecurityPolicy — write/external require human (ADV-12)',
    'WebhookSecurityPolicy — signature/timestamp/replay/idempotency',
    'APISecurityPolicy — auth/authz/rate/input/size/audit',
    'RateLimitPolicy — 5 scopes',
    'AbuseDetectionPolicy — 7 abuse patterns',
    'FileUploadSecurityPolicy — type/size/ext/path-traversal',
    'SecurityClientIsolationEvaluator — 10 domains, 100% enforced',
    'TenantSecurityContext — clientId+businessId+actor+role+scope+env',
    'PrivilegeEscalationDetector — 5 escalation types',
    'SecurityQualityScore — 10 factors',
    'PrivacyQualityScore — 11 factors',
    'GDPRTechnicalReadinessScore — 10 factors, NOT a legal certification',
    'CMPReadinessScore — 7 factors',
    '4 Quality Gates — Security/Privacy/GDPR/CMP',
    '7 bridges — BrowserQA/Observability/CICD/Production/Docker/Backup/Health',
    '6 fixture sets — security/privacy/cmp/gdpr/attack/failure',
  ]),
});
