// Social Content Registry Entry — ADV-14

export const SOCIAL_CONTENT_REGISTRY = Object.freeze({
  version:      '1.0.0',
  adv:          'ADV-14',
  name:         'Social Content Engine — Strategy + Generation + Calendar + QA + Make Bridge',
  totalModules: 45,
  guardrails: Object.freeze({
    FACTORY_AGENCY_SCOPE_ONLY: 'SI',
    NO_REAL_SOCIAL_PUBLISH:    'SI',
    NO_REAL_AD_SPEND:          'SI',
    NO_REAL_OUTREACH:          'SI',
    NO_REAL_EXTERNAL_COST:     'SI',
    ADS_EXECUTION:             'BLOCKED',
    MAKE_BRIDGE_MODE:          'DRY_RUN_ONLY',
  }),
  bridges: Object.freeze([
    'ADV-01 Observabilidad',
    'ADV-03 Agent Engine',
    'ADV-08 Lead Engine',
    'ADV-09 Agency CRM',
    'ADV-10 Langfuse/Humanness',
    'ADV-12 MCP Layer',
    'ADV-13 AI Media Engine',
  ]),
  modules: Object.freeze([
    'socialObjective', 'contentPillar', 'socialStrategyProfile',
    'socialCopyStyle', 'socialCadencePolicy', 'socialContentBrief',
    'resolveSocialStrategy', 'localBusinessContentPolicy', 'socialSeasonalityEngine',
    'contentNoveltyEngine', 'contentIdeaScore', 'generateContentIdeas',
    'socialHookEngine', 'socialCTAEngine', 'hashtagStrategy',
    'socialDiscoveryProfile', 'generateSocialPost',
    'resolveSocialMediaType',
    'instagramAdapter', 'facebookAdapter', 'tiktokAdapter',
    'youtubeAdapter', 'linkedinAdapter', 'xAdapter', 'threadsAdapter',
    'channelDifferentiationEvaluator',
    'repurposeContent', 'contentSeries',
    'socialContentCalendar', 'evaluateContentCalendarBalance',
    'socialContentQualityScore', 'socialContentQualityGate',
    'socialBrandConsistencyEvaluator', 'socialHumannessEvaluator',
    'socialContentApprovalPolicy', 'socialAdsPolicy',
    'socialChannelAuthStatus', 'socialContentPrivacyPolicy',
    'socialAutomationStatus', 'socialMakePayload', 'socialMakeBridge',
    'socialCampaign', 'generateSocialCampaignPlan',
    'socialMediaBridge', 'socialLeadEngineBridge', 'socialCRMBridge',
    'socialAgentBridge', 'socialMCPBridge', 'socialObservabilityBridge',
    'socialContentReport', 'socialEngineQualityScore',
  ]),
  fixtures: Object.freeze([
    'fixtureBusinesses', 'fixtureCampaigns', 'fixtureContentItems',
    'goodFixtures', 'failureFixtures', 'makePayloadFixtures',
  ]),
  contentFixtures: Object.freeze({ businesses: 7, campaigns: 20, contentItems: 80, failureFixtures: 13 }),
  qualityTargets: Object.freeze({
    minScore:        90,
    clientIsolation: 100,
    adsSafety:       100,
    makeSafety:      100,
  }),
  isReal: false,
});
