// Factory Registry — Voice Agent Engine (ADV-11)

export const VOICE_AGENT_REGISTRY = Object.freeze({
  moduleId:     'voice-agent',
  version:      '1.0.0',
  status:       '100_PERCENT',
  description:  'Humanized AI voice telephone agent engine — simulation only (NO_REAL_CALLS=SI)',
  adv:          'ADV-11',

  modules: Object.freeze([
    'voiceAgentProfile',
    'humanSpeechStyle',
    'voiceTurnManager',
    'bargeInPolicy',
    'voiceResponseLengthPolicy',
    'voicePausePolicy',
    'naturalDisfluencyPolicy',
    'honestIdentityPolicy',
    'voiceIntentModel',
    'voiceIntentSwitching',
    'voiceConversationMemory',
    'voiceConfirmationPolicy',
    'voiceRecoveryPolicy',
    'voiceUnderstandingConfidence',
    'silencePolicy',
    'voiceCallClosure',
    'voiceCallStateMachine',
    'voiceSafetyPolicy',
    'voicePrivacyPolicy',
    'recordingConsentPolicy',
    'voiceClientIsolation',
    'voiceEvaluationDimensions',
    'voiceHumannessScore',
    'voiceCallQualityScore',
    'voiceBusinessTruthBridge',
    'voiceAvailabilityBridge',
    'voiceBookingFlow',
    'voiceBusinessInfoFlow',
    'voiceSalesBehavior',
    'voiceSupportFlow',
    'voiceHumanHandoff',
    'voiceLeadQualificationFlow',
    'voiceCRMContext',
    'voiceProvider',
    'telephonyProvider',
    'ttsProvider',
    'sttProvider',
    'voiceProviderRouter',
    'spanishLanguageConfig',
    'voiceAccentProfile',
    'voicePersonalityByBusiness',
    'voiceChannelAdapter',
    'voiceLatencyBudget',
    'voiceFallbackPolicy',
    'voiceCostGuard',
    'voiceCostEstimate',
    'voiceCallReport',
    'voiceCommercialOutcome',
    'voiceObservabilityBridge',
    'voiceLangfuseBridge',
    'voiceAutomationManifest',
  ]),

  fixtures: Object.freeze([
    'bookingCallFixtures',
    'factualCallFixtures',
    'interruptionFixtures',
    'difficultCallFixtures',
    'salesCallFixtures',
    'callTranscriptSimulator',
    'simulatedCallDataset',
  ]),

  stats: Object.freeze({
    totalModules:    51,
    fixtureFiles:    7,
    simulatedCalls:  50,
    voiceVerticals:  7,
    statesMachine:   11,
    providerTypes:   4,
    evaluationDims:  6,
  }),

  guardrails: Object.freeze({
    NO_REAL_CALLS:     'SI',
    NO_REAL_COST:      'SI',
    NO_REAL_SMS:       'SI',
    NO_REAL_WHATSAPP:  'SI',
    NO_REAL_CLIENT_DATA:'SI',
  }),
});
