/**
 * VERTICAL · Abogados · Mock data
 * Datos 100% ficticios para demo interna.
 * Emails: @demo.ficticio  ·  Teléfonos: 600 000 03x  ·  Expedientes: EXP-00x-2026 (ficticio)
 * Juzgados, partes, cuantías: todos ficticios. No representan casos reales.
 */

export const MOCK_CLIENTES_ABOGADOS = [
  {
    id:                'cli001',
    nombre:            'Carlos Vega (ficticio)',
    email:             'carlos.v@demo.ficticio',
    telefono:          '600 000 031',
    area:              'laboral',
    area_label:        'Derecho Laboral',
    asunto:            'Despido improcedente (ficticio)',
    numero_expediente: 'EXP-001-2026 (ficticio)',
    fase:              'procedimiento_judicial',
    abogado:           'Dra. Martínez García (ficticia)',
    fecha_proxima_actuacion: '2026-09-10 (ficticio)',
    actuacion_pendiente:     'Vista oral en Juzgado Social nº3 (ficticio)',
    urgencia:          'alta',
    estado:            'expediente_abierto',
    origen:            'Web (ficticio)',
  },
  {
    id:                'cli002',
    nombre:            'Ana Jiménez (ficticia)',
    email:             'ana.j@demo.ficticio',
    telefono:          '600 000 032',
    area:              'familia',
    area_label:        'Derecho de Familia',
    asunto:            'Divorcio de mutuo acuerdo (ficticio)',
    numero_expediente: 'EXP-002-2026 (ficticio)',
    fase:              'negociacion',
    abogado:           'Dra. López Sánchez (ficticia)',
    fecha_proxima_actuacion: '2026-09-05 (ficticio)',
    actuacion_pendiente:     'Firma del convenio regulador (ficticio)',
    urgencia:          'baja',
    estado:            'en_proceso',
    origen:            'Referido (ficticio)',
  },
  {
    id:                'cli003',
    nombre:            'Miguel Torres (ficticio)',
    email:             'miguel.t@demo.ficticio',
    telefono:          '600 000 033',
    area:              'civil',
    area_label:        'Derecho Civil',
    asunto:            'Reclamación de cantidad por contrato incumplido (ficticio)',
    numero_expediente: 'EXP-003-2026 (ficticio)',
    fase:              'investigacion',
    abogado:           'D. Fernández Ruiz (ficticio)',
    fecha_proxima_actuacion: '2026-09-15 (ficticio)',
    actuacion_pendiente:     'Envío de burofax requerimiento (ficticio)',
    urgencia:          'media',
    estado:            'consulta_realizada',
    origen:            'Google (ficticio)',
  },
  {
    id:                'cli004',
    nombre:            'Elena Moreno (ficticia)',
    email:             'elena.m@demo.ficticio',
    telefono:          '600 000 034',
    area:              'mercantil',
    area_label:        'Derecho Mercantil',
    asunto:            'Constitución de sociedad limitada (ficticio)',
    numero_expediente: 'EXP-004-2026 (ficticio)',
    fase:              'consulta_inicial',
    abogado:           'D. Fernández Ruiz (ficticio)',
    fecha_proxima_actuacion: '2026-08-30 (ficticio)',
    actuacion_pendiente:     'Preparación de estatutos sociales (ficticio)',
    urgencia:          'baja',
    estado:            'nuevo',
    origen:            'Campaña laboral (ficticio)',
  },
  {
    id:                'cli005',
    nombre:            'Roberto Navarro (ficticio)',
    email:             'roberto.n@demo.ficticio',
    telefono:          '600 000 035',
    area:              'administrativo',
    area_label:        'Derecho Administrativo',
    asunto:            'Recurso de multa de tráfico (ficticio)',
    numero_expediente: 'EXP-005-2026 (ficticio)',
    fase:              'resolucion',
    abogado:           'Dra. Martínez García (ficticia)',
    fecha_proxima_actuacion: null,
    actuacion_pendiente:     'Pendiente resolución administrativa (ficticio)',
    urgencia:          'baja',
    estado:            'en_proceso',
    origen:            'Instagram (ficticio)',
  },
];

export const MOCK_METRICAS_ABOGADOS = {
  consultas_mes:              32,
  expedientes_activos:        18,
  tasa_conversion_consulta:   61,
  oportunidades_recuperadas:  5,
  valor_pipeline:             '38.400 € (ficticio)',
  facturacion_mes:            '12.800 € (ficticio)',
  por_area: [
    { area: 'Laboral',       casos: 12 },
    { area: 'Familia',       casos: 8  },
    { area: 'Civil',         casos: 6  },
    { area: 'Mercantil',     casos: 4  },
    { area: 'Penal',         casos: 2  },
  ],
  por_abogado: [
    { abogado: 'Dra. Martínez', expedientes: 9 },
    { abogado: 'Dra. López',    expedientes: 7 },
    { abogado: 'D. Fernández',  expedientes: 5 },
    { abogado: 'D. Rodríguez',  expedientes: 3 },
  ],
  por_fase: [
    { fase: 'Consulta inicial',  casos: 5 },
    { fase: 'Investigación',     casos: 4 },
    { fase: 'Negociación',       casos: 6 },
    { fase: 'Proc. judicial',    casos: 3 },
  ],
};

export const MOCK_LEADS_ABANDONO_ABOGADOS = [
  {
    id:               'lab001',
    nombre:           'Lucía Castillo (ficticia)',
    email:            'lucia.c@demo.ficticio',
    telefono:         '600 000 036',
    area:             'laboral',
    asunto_interes:   'Accidente laboral',
    estado_abandono:  'no_confirmo_consulta',
    dias_inactivo:    4,
    accion_sugerida:  'Recordatorio: consulta gratuita campaña laboral',
    estado:           'en_proceso',
  },
  {
    id:               'lab002',
    nombre:           'Fernando Gil (ficticio)',
    email:            'fernando.g@demo.ficticio',
    telefono:         '600 000 037',
    area:             'familia',
    asunto_interes:   'Herencia en disputa',
    estado_abandono:  'consulto_honorarios',
    dias_inactivo:    7,
    accion_sugerida:  'Ofrecer presupuesto cerrado para herencias',
    estado:           'en_proceso',
  },
  {
    id:               'lab003',
    nombre:           'Patricia Ruiz (ficticia)',
    email:            'patricia.r@demo.ficticio',
    telefono:         '600 000 038',
    area:             'civil',
    asunto_interes:   'Deuda de comunidad de vecinos',
    estado_abandono:  'abandono_formulario',
    dias_inactivo:    12,
    accion_sugerida:  'Email seguimiento con caso similar resuelto',
    estado:           'recuperado',
  },
];

export const MOCK_SLOTS_ABOGADOS = [
  {
    id:          'sla001',
    fecha:       '2026-09-01 (ficticio)',
    hora:        '10:00',
    despacho:    'Despacho Central (ficticio)',
    abogado:     'Dra. Martínez García (ficticia)',
    area:        'laboral',
    disponible:  true,
  },
  {
    id:          'sla002',
    fecha:       '2026-09-02 (ficticio)',
    hora:        '16:30',
    despacho:    'Despacho Central (ficticio)',
    abogado:     'Dra. López Sánchez (ficticia)',
    area:        'familia',
    disponible:  true,
  },
  {
    id:          'sla003',
    fecha:       '2026-09-03 (ficticio)',
    hora:        '11:00',
    despacho:    'Sucursal Norte (ficticio)',
    abogado:     'D. Fernández Ruiz (ficticio)',
    area:        'civil_mercantil',
    disponible:  true,
  },
];

export const MOCK_TAREAS_PROXIMAS = [
  {
    id:          'tar001',
    expediente:  'EXP-001-2026 (ficticio)',
    cliente:     'Carlos Vega (ficticio)',
    tarea:       'Vista oral en Juzgado Social nº3 (ficticio)',
    fecha:       '2026-09-10 (ficticio)',
    abogado:     'Dra. Martínez García (ficticia)',
    urgencia:    'alta',
  },
  {
    id:          'tar002',
    expediente:  'EXP-002-2026 (ficticio)',
    cliente:     'Ana Jiménez (ficticia)',
    tarea:       'Firma del convenio regulador (ficticio)',
    fecha:       '2026-09-05 (ficticio)',
    abogado:     'Dra. López Sánchez (ficticia)',
    urgencia:    'media',
  },
  {
    id:          'tar003',
    expediente:  'EXP-003-2026 (ficticio)',
    cliente:     'Miguel Torres (ficticio)',
    tarea:       'Envío de burofax requerimiento (ficticio)',
    fecha:       '2026-09-15 (ficticio)',
    abogado:     'D. Fernández Ruiz (ficticio)',
    urgencia:    'baja',
  },
];
