// CLIENTE: provisional generated resources explicitly approved for local review only.
export const EDUCATIONAL_CATALOG = [
  {
    "id": "01-reglas-del-padel",
    "title": "Reglas del pádel",
    "video": "/media/club-padel-04/educational-provisional-v1/01-reglas-del-padel.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/01-reglas.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/01-poster.jpg",
    "transcript": "El pádel se juega normalmente por parejas. El saque es por debajo de la cintura, tras un bote, y en diagonal. La pelota debe botar antes de tocar la pared rival. Puedes devolverla antes del segundo bote y usar tu propia pared después del bote. Son faltas frecuentes sacar por encima de la cintura, enviar la pelota fuera o dejar que bote dos veces. Control y colocación mandan.",
    "duration": 30,
    "order": 0,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "b0bddfcf54f29f2d673e200c39b8ef1b94f737c3217e3035801da638a4b0b680",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "02-formas-de-ganar-puntos",
    "title": "Formas de ganar puntos",
    "video": "/media/club-padel-04/educational-provisional-v1/02-formas-de-ganar-puntos.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/02-formas-de-puntuar.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/02-poster.jpg",
    "transcript": "No todos los puntos se ganan con potencia. Una volea colocada puede abrir el espacio y obligar al error. La bandeja mantiene la red con seguridad. El globo desplaza a los rivales y permite recuperar una posición ofensiva. Cuando la pelota queda alta, el remate puede cerrar el punto. La mejor elección depende de la altura, el espacio y la posición rival.",
    "duration": 30,
    "order": 1,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "d02ca8d08bbcf352ddb38539126c4d0150e138508ad162bbbdc6c5152e1228b0",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "03-historia-del-padel",
    "title": "Historia del pádel",
    "video": "/media/club-padel-04/educational-provisional-v1/03-historia-del-padel.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/03-historia.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/03-poster.jpg",
    "transcript": "El pádel moderno nació en Acapulco, México, en 1969, cuando Enrique Corcuera adaptó un espacio rodeado por muros. En 1974, Alfonso de Hohenlohe llevó la idea a Marbella, España, donde comenzó su expansión europea. Argentina fue uno de los primeros grandes focos de crecimiento. Desde México, España y Argentina, el deporte se extendió por el mundo.",
    "duration": 30,
    "order": 2,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "25486dd7c8b7d63238e50f856b4562895391cede5f781992a078339e380dd2dd",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "04-curiosidades-del-padel",
    "title": "Curiosidades del pádel",
    "video": "/media/club-padel-04/educational-provisional-v1/04-curiosidades-del-padel.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/04-curiosidades.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/04-poster.jpg",
    "transcript": "Una pista reglamentaria mide veinte por diez metros y sus paredes forman parte activa del juego. La pala es sólida, sin cuerdas y perforada. La correa de muñeca es un elemento esencial de seguridad. Aunque se parece al tenis, el uso del cristal y el trabajo en pareja le dan una identidad táctica propia.",
    "duration": 20,
    "order": 3,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "8941f611b31e1e8a05db77b2c2f3382abbfd96b5ce082d881ad520b49b783fb5",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "05-sistema-de-puntuacion",
    "title": "Sistema de puntuación",
    "video": "/media/club-padel-04/educational-provisional-v1/05-sistema-de-puntuacion.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/05-puntuacion.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/05-poster.jpg",
    "transcript": "Cada juego avanza de cero a quince, treinta y cuarenta. Con empate a cuarenta se llega a iguales. Según la competición, se juega ventaja o punto decisivo. En punto decisivo, la pareja restadora elige el lado. Un set suele ganarse al llegar a seis juegos con dos de diferencia; si hay empate, el formato puede establecer un desempate.",
    "duration": 30,
    "order": 4,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "ba00f7139fd08e2449f1f6eb98100dfe05e7238fa0a5914975c8c5f68198e802",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "06-material-deportivo",
    "title": "Material deportivo",
    "video": "/media/club-padel-04/educational-provisional-v1/06-material-deportivo.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/06-material.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/06-poster.jpg",
    "transcript": "Para jugar necesitas una pala adecuada, pelotas de pádel y zapatillas con agarre compatible con la superficie. El overgrip mejora el control. La correa de muñeca aporta seguridad y un protector ayuda a cuidar el marco. Ropa transpirable, gorra, agua y una cesta o carro de bolas completan un equipo práctico para entrenar con comodidad.",
    "duration": 30,
    "order": 5,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "aeae5463d4885350a17fc8748000bcf22999896bd46cc3b69fdbc9205a14fb39",
    "license": null,
    "realFootageGate": "PENDING"
  },
  {
    "id": "07-guia-para-tu-primer-partido",
    "title": "Guía para tu primer partido",
    "video": "/media/club-padel-04/educational-provisional-v1/07-guia-para-tu-primer-partido.mp4",
    "subtitles": "/media/club-padel-04/educational-provisional-v1/07-primer-partido.vtt",
    "poster": "/media/club-padel-04/educational-provisional-v1/07-poster.jpg",
    "transcript": "Antes de tu primer partido, calienta, hidrátate, revisa el calzado y ajusta siempre la correa de la pala. Habla con tu pareja, muévete con ella y recupera la posición después de cada golpe. La colocación vale más que la fuerza. Respeta el turno, recoge las pelotas y saluda al terminar. Empieza con control: la regularidad hará el juego más divertido y seguro.",
    "duration": 30,
    "order": 6,
    "kind": "provisional_generated",
    "status": "LOCAL_PREVIEW_USER_APPROVED",
    "sha256": "023910f5df607c3a0ddc9690bc500612bbea760abb8443a044199b237a547146",
    "license": null,
    "realFootageGate": "PENDING"
  }
];
export const EDUCATIONAL_PREVIEW_ENABLED = import.meta.env?.DEV === true;
