/**
 * App Shell Recipes V2 — 7 variants
 */

export const APP_SHELL_RECIPES = Object.freeze([
  {
    id: 'shell-sidebar-fixed',
    name: 'Sidebar Fixed',
    description: 'Fixed left sidebar navigation with main content area',
    layout: 'sidebar-main',
    sidebarWidth: 256,
    collapsible: false,
    elements: ['logo', 'nav-links', 'user-section', 'main-content', 'topbar'],
    presets: ['data-heavy-saas', 'tech-futuristic', 'professional-authority'],
    motionSuggestion: 'PageTransition on route change',
    breakpoint: 'lg',
  },
  {
    id: 'shell-sidebar-collapsible',
    name: 'Sidebar Collapsible',
    description: 'Collapsible sidebar that folds to icon-only mode',
    layout: 'sidebar-main',
    sidebarWidth: 240,
    collapsibleWidth: 64,
    collapsible: true,
    elements: ['logo', 'nav-links-icons', 'collapse-toggle', 'main-content', 'topbar'],
    presets: ['data-heavy-saas', 'tech-futuristic'],
    motionSuggestion: 'LayoutTransition on width change, icon tooltips via Tooltip',
    breakpoint: 'md',
  },
  {
    id: 'shell-topbar',
    name: 'Top Navigation Bar',
    description: 'Horizontal top nav with dropdown menus, mobile hamburger',
    layout: 'topbar-main',
    elements: ['logo', 'nav-links', 'user-menu', 'search', 'notifications', 'main-content'],
    presets: ['minimal-premium', 'clinical-premium', 'education-interactive'],
    motionSuggestion: 'Dropdown reveals with Popover + fade, MotionDrawer for mobile',
    sticky: true,
    transparent: false,
  },
  {
    id: 'shell-landing',
    name: 'Landing Page Shell',
    description: 'Marketing landing page layout — nav + hero + sections + footer',
    layout: 'landing',
    elements: ['sticky-nav', 'hero', 'sections', 'footer'],
    presets: ['*'],
    motionSuggestion: 'Nav hides on scroll down, shows on scroll up',
    stickyNav: true,
    progressBar: false,
  },
  {
    id: 'shell-dashboard-grid',
    name: 'Dashboard Grid',
    description: 'App dashboard with metric cards, charts, and data tables',
    layout: 'dashboard',
    elements: ['topbar', 'metric-row', 'chart-area', 'data-table', 'sidebar-panel'],
    presets: ['data-heavy-saas', 'tech-futuristic'],
    motionSuggestion: 'Metric cards stagger in, chart animates on mount',
    responsive: true,
  },
  {
    id: 'shell-tabs-main',
    name: 'Tabbed Main Area',
    description: 'Main content area with persistent top tabs',
    layout: 'tabs-main',
    elements: ['header', 'motion-tabs', 'tab-panels'],
    presets: ['education-interactive', 'clinical-premium', 'professional-authority'],
    motionSuggestion: 'MotionTabs for indicator, PageTransition between panels',
    tabPosition: 'top',
  },
  {
    id: 'shell-split-panel',
    name: 'Split Panel',
    description: 'Two-panel layout — list on left, detail on right',
    layout: 'split-panel',
    elements: ['list-panel', 'detail-panel', 'topbar'],
    presets: ['professional-authority', 'data-heavy-saas'],
    motionSuggestion: 'Detail panel fades in with PageTransition',
    leftWidth: '38%',
    rightWidth: '62%',
  },
]);
