/**
 * Conversion Section Recipes V2 — 6 variants
 */

export const CONVERSION_RECIPES = Object.freeze([
  {
    id: 'conversion-cta-band',
    name: 'CTA Band',
    description: 'Full-width color band with headline and primary CTA',
    layout: 'band',
    elements: ['gradient-bg', 'headline', 'subtitle', 'cta-primary'],
    presets: ['*'],
    motionSuggestion: 'Reveal on scroll, CTA has MotionButton',
    urgency: false,
  },
  {
    id: 'conversion-pricing-cards',
    name: 'Pricing Cards',
    description: '3-tier pricing with feature list and highlighted recommended plan',
    layout: '3col-pricing',
    elements: ['section-header', 'pricing-cards', 'faq-link'],
    cardElements: ['plan-name', 'price', 'billing-cycle', 'feature-list', 'cta', 'badge'],
    presets: ['tech-futuristic', 'minimal-premium', 'professional-authority'],
    motionSuggestion: 'Cards stagger in, recommended plan scales 1.02',
    recommendedPlanHighlight: true,
  },
  {
    id: 'conversion-booking-teaser',
    name: 'Booking Teaser',
    description: 'Appointment/booking prompt with availability and trust signals',
    layout: 'booking-split',
    elements: ['headline', 'availability-badge', 'benefit-list', 'cta-booking', 'trust-signals'],
    presets: ['clinical-premium', 'friendly-human', 'sports-dynamic'],
    motionSuggestion: 'Pulse on availability badge, Reveal on content',
    usps: ['fast-response', 'no-commitment', 'free-consultation'],
  },
  {
    id: 'conversion-lead-capture',
    name: 'Lead Capture Form',
    description: 'Email/contact capture with value proposition',
    layout: 'split-form',
    elements: ['value-prop', 'form-card', 'privacy-note'],
    cardElements: ['name-input', 'email-input', 'phone-input', 'submit-button', 'consent'],
    presets: ['professional-authority', 'tech-futuristic', 'education-interactive'],
    motionSuggestion: 'Form slides from right, fields stagger in',
    fieldCount: 3,
    privacyRequired: true,
  },
  {
    id: 'conversion-faq',
    name: 'FAQ Accordion',
    description: 'Frequently asked questions with expandable answers',
    layout: 'accordion',
    elements: ['section-header', 'faq-list', 'contact-cta'],
    cardElements: ['question', 'answer', 'expand-icon'],
    presets: ['*'],
    motionSuggestion: 'LayoutTransition height, icon rotates 180deg',
    minFaqs: 5,
    maxFaqs: 12,
  },
  {
    id: 'conversion-urgency-banner',
    name: 'Urgency/Offer Banner',
    description: 'Limited time offer with countdown and strong CTA',
    layout: 'urgency-strip',
    elements: ['offer-text', 'countdown-timer', 'cta-primary', 'close-button'],
    presets: ['sports-dynamic', 'friendly-human'],
    motionSuggestion: 'Slides down from top, timer ticks with AnimatedMetric',
    urgency: true,
    sticky: false,
    requiresCountdown: true,
  },
]);
