/**
 * Dashboard Section Recipes V2 — 8 variants
 */

export const DASHBOARD_RECIPES = Object.freeze([
  {
    id: 'dashboard-metrics-row',
    name: 'Metrics Overview Row',
    description: '4-6 KPI cards with icon, value, delta, trend',
    layout: 'row',
    elements: ['metric-cards'],
    cardElements: ['icon', 'label', 'value', 'delta', 'trend-sparkline'],
    presets: ['data-heavy-saas', 'tech-futuristic'],
    motionSuggestion: 'AnimatedMetric for each value, stagger 60ms',
    minMetrics: 4,
    maxMetrics: 6,
  },
  {
    id: 'dashboard-chart-area',
    name: 'Main Chart Area',
    description: 'Primary chart with time selector and data toggle',
    layout: 'full-width-chart',
    elements: ['chart-header', 'time-selector', 'chart-body', 'legend'],
    presets: ['data-heavy-saas', 'tech-futuristic', 'professional-authority'],
    motionSuggestion: 'Chart draws in from left on mount',
    chartTypes: ['line', 'bar', 'area'],
    timePeriods: ['7d', '30d', '90d', '1y'],
  },
  {
    id: 'dashboard-activity-feed',
    name: 'Activity Feed',
    description: 'Chronological activity list with type icons and timestamps',
    layout: 'feed',
    elements: ['feed-header', 'activity-items', 'load-more'],
    cardElements: ['icon', 'description', 'timestamp', 'actor', 'optional-badge'],
    presets: ['*'],
    motionSuggestion: 'New items animate in from top with MotionCard',
    maxVisible: 10,
    realtimeReady: true,
  },
  {
    id: 'dashboard-data-table',
    name: 'Data Table',
    description: 'Sortable, filterable data table with row actions',
    layout: 'table',
    elements: ['table-header', 'search-filter', 'table-body', 'pagination'],
    cardElements: ['th', 'td', 'sort-indicator', 'row-action-menu'],
    presets: ['data-heavy-saas', 'professional-authority'],
    motionSuggestion: 'Rows stagger in, sort transition with LayoutTransition',
    features: ['sort', 'filter', 'paginate', 'row-actions'],
  },
  {
    id: 'dashboard-status-grid',
    name: 'Status Grid',
    description: 'Grid of status cards (services, rooms, machines, etc)',
    layout: 'grid-status',
    elements: ['header', 'status-cards', 'legend'],
    cardElements: ['name', 'status-indicator', 'status-label', 'detail'],
    presets: ['tech-futuristic', 'data-heavy-saas', 'clinical-premium'],
    motionSuggestion: 'Status changes animate with MotionCard, color transitions',
    statuses: ['active', 'inactive', 'warning', 'error'],
  },
  {
    id: 'dashboard-progress-overview',
    name: 'Progress Overview',
    description: 'Multi-item progress bars with labels and percentages',
    layout: 'progress-list',
    elements: ['section-header', 'progress-rows'],
    cardElements: ['label', 'value', 'MotionProgress', 'percentage'],
    presets: ['education-interactive', 'clinical-premium', 'sports-dynamic'],
    motionSuggestion: 'MotionProgress animates from 0 on mount, stagger 80ms',
    maxItems: 8,
  },
  {
    id: 'dashboard-calendar-mini',
    name: 'Mini Calendar',
    description: 'Month view calendar with event indicators',
    layout: 'calendar',
    elements: ['month-nav', 'day-grid', 'event-dots'],
    presets: ['clinical-premium', 'education-interactive', 'sports-dynamic'],
    motionSuggestion: 'Month transitions with slide left/right',
    features: ['event-indicators', 'today-highlight', 'day-selection'],
  },
  {
    id: 'dashboard-profile-card',
    name: 'User Profile Card',
    description: 'User profile with stats, recent activity, quick actions',
    layout: 'profile-card',
    elements: ['avatar', 'name', 'role', 'stats-row', 'quick-actions', 'recent-items'],
    presets: ['*'],
    motionSuggestion: 'Stats count up with AnimatedMetric, actions have MotionButton',
    orientation: 'vertical',
  },
]);
