/**
 * Feature Section Recipes V2 — 8 variants
 */

export const FEATURE_RECIPES = Object.freeze([
  {
    id: 'features-3col-icons',
    name: 'Features 3-Column Icons',
    description: '3 columns, icon + title + description per feature',
    layout: '3col',
    elements: ['section-label', 'headline', 'subheadline', 'feature-cards-3'],
    cardElements: ['icon', 'title', 'description'],
    presets: ['clinical-premium', 'professional-authority', 'friendly-human'],
    motionSuggestion: 'Stagger cards 80ms each',
    maxFeatures: 6,
  },
  {
    id: 'features-alternating',
    name: 'Features Alternating Rows',
    description: 'Text + image alternating layout for detailed features',
    layout: 'alternating',
    elements: ['section-header', 'feature-row-left', 'feature-row-right'],
    cardElements: ['icon', 'title', 'description', 'benefit-list', 'media'],
    presets: ['minimal-premium', 'education-interactive', 'professional-authority'],
    motionSuggestion: 'Each row slides from alternate side on scroll',
    maxFeatures: 4,
  },
  {
    id: 'features-tabs',
    name: 'Features Tabbed',
    description: 'Tabbed feature explorer — one feature detailed at a time',
    layout: 'tabs',
    elements: ['section-header', 'tab-list', 'feature-panel'],
    cardElements: ['tab-icon', 'tab-label', 'content-headline', 'content-body', 'screenshot'],
    presets: ['tech-futuristic', 'data-heavy-saas'],
    motionSuggestion: 'Indicator slides with MotionTabs, panel fades in',
    maxFeatures: 6,
  },
  {
    id: 'features-numbered',
    name: 'Features Numbered Steps',
    description: 'How-it-works style with large numbers',
    layout: 'numbered',
    elements: ['section-header', 'numbered-steps', 'cta'],
    cardElements: ['step-number', 'title', 'description', 'optional-icon'],
    presets: ['friendly-human', 'education-interactive', 'clinical-premium'],
    motionSuggestion: 'Numbers count in, connector lines draw on scroll',
    maxFeatures: 5,
  },
  {
    id: 'features-grid-glass',
    name: 'Features Glass Grid',
    description: 'Glass card grid for dark/luxury presets',
    layout: 'grid',
    elements: ['gradient-bg', 'section-header', 'glass-cards'],
    cardElements: ['icon', 'title', 'description', 'optional-badge'],
    presets: ['luxury-editorial', 'tech-futuristic', 'immersive-showcase'],
    motionSuggestion: 'Cards reveal in stagger with blur-in effect',
    maxFeatures: 8,
    requiresGlass: true,
  },
  {
    id: 'features-comparison',
    name: 'Features Comparison Table',
    description: 'Before/after or competitor comparison',
    layout: 'comparison',
    elements: ['section-header', 'comparison-table', 'cta'],
    cardElements: ['category', 'before-value', 'after-value', 'checkmark'],
    presets: ['professional-authority', 'tech-futuristic'],
    motionSuggestion: 'Rows stagger in, checkmarks pop on visible',
    maxFeatures: 8,
  },
  {
    id: 'features-map',
    name: 'Features Icon Map',
    description: 'Central product image with floating feature callouts',
    layout: 'map',
    elements: ['central-visual', 'feature-callouts'],
    cardElements: ['position', 'icon', 'label', 'description'],
    presets: ['tech-futuristic', 'immersive-showcase'],
    motionSuggestion: 'Callouts float in from positions with spring delay',
    maxFeatures: 6,
  },
  {
    id: 'features-accordion',
    name: 'Features Accordion',
    description: 'Expandable feature list for detailed content',
    layout: 'accordion',
    elements: ['section-header', 'accordion-items'],
    cardElements: ['icon', 'title', 'expanded-content', 'media'],
    presets: ['professional-authority', 'education-interactive'],
    motionSuggestion: 'LayoutTransition for height change, icon rotates',
    maxFeatures: 8,
  },
]);
