/**
 * Hero Section Recipes V2 — 8 variants
 */

export const HERO_RECIPES = Object.freeze([
  {
    id: 'hero-centered-text',
    name: 'Hero Centered Text',
    description: 'Full-width centered headline, subtitle, dual CTA',
    layout: 'centered',
    elements: ['headline', 'subtitle', 'cta-primary', 'cta-secondary', 'badge'],
    presets: ['minimal-premium', 'professional-authority', 'clinical-premium'],
    motionSuggestion: 'Reveal fade-in, subtitle stagger 100ms after headline',
    minHeight: '60vh',
    contentWidth: '680px',
    example: {
      headline: 'La solución profesional que necesitas',
      subtitle: 'Diseñado para crecer con tu negocio. Más de 2.000 empresas confían en nosotros.',
      ctaPrimary: 'Comenzar ahora',
      ctaSecondary: 'Ver demo',
    },
  },
  {
    id: 'hero-split-content',
    name: 'Hero Split Content',
    description: 'Left text + right image/visual, 50/50 or 55/45 split',
    layout: 'split',
    elements: ['headline', 'subtitle', 'cta-primary', 'cta-secondary', 'media', 'trust-badges'],
    presets: ['clinical-premium', 'friendly-human', 'education-interactive'],
    motionSuggestion: 'Text slides from left, image from right, stagger 150ms',
    minHeight: '70vh',
    contentWidth: '100%',
    example: {
      headline: 'Transformamos tu negocio digital',
      subtitle: 'Soluciones a medida para empresas que quieren crecer.',
      ctaPrimary: 'Solicitar consulta',
      mediaType: 'illustration',
    },
  },
  {
    id: 'hero-video-background',
    name: 'Hero Video Background',
    description: 'Full-bleed autoplay video with overlay text and gradient',
    layout: 'full-bleed',
    elements: ['video', 'overlay-gradient', 'headline', 'subtitle', 'cta-primary'],
    presets: ['sports-dynamic', 'luxury-editorial', 'immersive-showcase'],
    motionSuggestion: 'Text fades in after 600ms, subtle parallax scroll',
    minHeight: '100vh',
    contentWidth: '820px',
    requirements: ['video-url', 'poster-image'],
    example: {
      headline: 'Supera tus límites',
      videoHint: 'Club en acción, pistas, entrenamientos',
      ctaPrimary: 'Únete al club',
    },
  },
  {
    id: 'hero-mesh-gradient',
    name: 'Hero Mesh Gradient',
    description: 'Animated mesh gradient background with glass card content',
    layout: 'centered-glass',
    elements: ['mesh-bg', 'glass-card', 'headline', 'subtitle', 'cta-primary', 'metrics-row'],
    presets: ['tech-futuristic', 'minimal-premium'],
    motionSuggestion: 'Background animates slowly, card slides up with spring',
    minHeight: '80vh',
    contentWidth: '720px',
    example: {
      headline: 'El futuro de tu negocio empieza aquí',
      metricsHint: '3 key metrics below headline',
    },
  },
  {
    id: 'hero-editorial-bold',
    name: 'Hero Editorial Bold',
    description: 'Large display typography, minimal UI, strong visual hierarchy',
    layout: 'editorial',
    elements: ['big-number', 'category-label', 'headline-display', 'body', 'cta-primary', 'divider'],
    presets: ['luxury-editorial', 'immersive-showcase'],
    motionSuggestion: 'Text reveals character by character, stagger 20ms per char',
    minHeight: '90vh',
    contentWidth: '1000px',
    example: {
      displayNumber: '2024',
      headline: 'Excelencia sin compromisos',
      body: 'Una experiencia diseñada para quienes exigen lo mejor.',
    },
  },
  {
    id: 'hero-split-stats',
    name: 'Hero Split with Stats',
    description: 'Left content, right animated metrics grid',
    layout: 'split-stats',
    elements: ['headline', 'body', 'cta-primary', 'stats-grid', 'trust-strip'],
    presets: ['professional-authority', 'data-heavy-saas', 'tech-futuristic'],
    motionSuggestion: 'Stats count up on mount, stagger 200ms each',
    minHeight: '70vh',
    contentWidth: '100%',
    example: {
      stats: [
        { value: 2400, label: 'Clientes activos' },
        { value: 98, label: '% Satisfacción', suffix: '%' },
        { value: 15, label: 'Años de experiencia', suffix: '+' },
      ],
    },
  },
  {
    id: 'hero-product-showcase',
    name: 'Hero Product Showcase',
    description: 'App/product UI mockup as the hero visual, feature callouts',
    layout: 'product-center',
    elements: ['app-mockup', 'callout-cards', 'headline', 'subtitle', 'cta-primary', 'cta-secondary'],
    presets: ['tech-futuristic', 'data-heavy-saas'],
    motionSuggestion: 'Mockup scales in from 0.9, callouts stagger from sides',
    minHeight: '85vh',
    contentWidth: '1100px',
    example: {
      mockupType: 'dashboard-screenshot',
      callouts: ['Analytics en tiempo real', 'Multi-tenant', 'APIs abiertas'],
    },
  },
  {
    id: 'hero-local-community',
    name: 'Hero Local Community',
    description: 'Warm, human hero for local businesses — photo collage + social proof',
    layout: 'community',
    elements: ['photo-collage', 'headline', 'subtitle', 'cta-primary', 'social-count', 'rating'],
    presets: ['friendly-human', 'sports-dynamic'],
    motionSuggestion: 'Photos fade in staggered, headline slides up',
    minHeight: '65vh',
    contentWidth: '100%',
    example: {
      rating: 4.9,
      reviewCount: 320,
      communitySize: '1.200 miembros',
    },
  },
]);
