/**
 * Factory Interactive Patterns Recipe Registry
 * Derived from FisioNova Premium V2 Pilot validated patterns.
 * Each entry is a reusable, vertical-agnostic interaction recipe.
 *
 * Fields:
 *   id, purpose, allowedVerticals, mobileSafe, a11y,
 *   motionTier, functionalRequirements, fallback, testRequirements
 */

export const INTERACTIVE_PATTERN_RECIPES = Object.freeze([
  {
    id: 'booking-flow',
    name: 'Multi-Step Booking Flow',
    purpose: 'Guide users through service selection → schedule → confirm → success',
    pattern: 'modal',
    steps: ['service-selection', 'date-time', 'confirmation', 'success'],
    allowedVerticals: ['*'],
    mobileSafe: true,
    a11y: {
      role: 'dialog',
      ariaModal: true,
      ariaLabel: 'Solicitar cita',
      keyboardDismiss: 'Escape',
      focusTrap: true,
    },
    motionTier: 'medium',
    motion: {
      overlay: 'overlayIn (.2s fade)',
      modal: 'modalIn (.32s spring)',
      success: 'successPop (.5s spring)',
    },
    functionalRequirements: ['onComplete', 'steps', 'serviceOptions', 'timeSlots'],
    fallback: 'redirect-to-contact-form',
    testRequirements: [
      'step 1 canNext requires service selected',
      'step 2 canNext requires date AND time',
      'step 3 shows confirmation summary',
      'step 4 shows success state',
      'escape key closes modal',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'responsive-sidebar',
    name: 'Responsive Collapsible Sidebar',
    purpose: 'Primary navigation that collapses on mobile and becomes an overlay',
    pattern: 'navigation',
    allowedVerticals: ['*'],
    mobileSafe: true,
    mobileBreakpoint: 768,
    collapsedWidth: 56,
    expandedWidth: 220,
    mobileWidth: 260,
    a11y: {
      role: 'navigation',
      ariaLabel: 'Navegación principal',
      ariaCurrent: 'page',
      keyboardCollapse: true,
    },
    motionTier: 'low',
    motion: {
      collapse: 'width .25s cubic-bezier(.22,1,.36,1)',
      overlay: 'backdrop fade .2s',
    },
    functionalRequirements: [
      'onNav',
      'mobileHamburger',
      'mobileOverlay',
      'onClose (mobile)',
      'collapsed state',
      'onToggleCollapse',
    ],
    logoRequirements: [
      'icon always visible (even collapsed)',
      'text hidden when collapsed',
      'minWidth:0 on text to prevent overflow',
      'flexShrink:0 on icon',
    ],
    fallback: 'topbar-horizontal-nav',
    testRequirements: [
      'isMobile true when width < 768',
      'hamburger button present on mobile',
      'sidebar is overlay on mobile',
      'escape key closes mobile sidebar',
      'logo icon always visible',
      'logo text hidden when collapsed',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'mobile-overlay-nav',
    name: 'Mobile Overlay Navigation',
    purpose: 'Full-screen overlay sidebar activated by hamburger button',
    pattern: 'navigation',
    allowedVerticals: ['*'],
    mobileSafe: true,
    mobileBreakpoint: 768,
    a11y: {
      ariaExpanded: true,
      ariaLabel: 'Abrir menú',
      keyboardDismiss: 'Escape',
      backdropClick: true,
    },
    motionTier: 'low',
    functionalRequirements: ['onOpen', 'onClose', 'isOpen'],
    fallback: 'bottom-tab-nav',
    testRequirements: [
      'hamburger opens sidebar',
      'backdrop click closes sidebar',
      'escape closes sidebar',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'role-switcher',
    name: 'Role Switcher',
    purpose: 'Allow demo users to switch between personas/roles and see role-specific UX',
    pattern: 'roleSwitcher',
    allowedVerticals: ['*'],
    mobileSafe: true,
    roles: 'configurable per vertical',
    mobileVariant: 'select-dropdown',
    desktopVariant: 'pill-buttons',
    a11y: {
      ariaLabel: 'Cambiar rol',
      keyboardSelectable: true,
    },
    motionTier: 'none',
    functionalRequirements: ['onRoleChange', 'roles', 'activeRole'],
    behavior: [
      'role change redirects to first allowed view',
      'each role sees only permitted modules',
      'visual distinction per role (color + icon)',
      'mobile uses native select for accessibility',
    ],
    testRequirements: [
      'admin sees all modules',
      'recepcion sees only allowed modules',
      'paciente sees only allowed modules',
      'role change triggers first allowed view navigation',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'action-feedback',
    name: 'Action Feedback State',
    purpose: 'Provide visual confirmation after user actions (confirm, cancel, save)',
    pattern: 'actionFeedback',
    allowedVerticals: ['*'],
    mobileSafe: true,
    types: ['success', 'error', 'info', 'warning'],
    behavior: [
      'replaces action buttons with outcome state',
      'auto-closes or auto-dismisses after delay',
      'never leaves user in ambiguous state',
    ],
    a11y: {
      role: 'status',
      ariaLive: 'polite',
    },
    motionTier: 'low',
    motion: { enter: 'fade + scale .3s' },
    functionalRequirements: ['type', 'message'],
    testRequirements: [
      'action replaces buttons with feedback state',
      'feedback shows correct icon for type',
      'auto-dismiss fires after configured delay',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'loading-pattern',
    name: 'Loading Skeleton Pattern',
    purpose: 'Show shimmer skeletons while content loads, never blank screens',
    pattern: 'loadingState',
    allowedVerticals: ['*'],
    mobileSafe: true,
    variants: ['list-skeleton', 'card-skeleton', 'chart-skeleton', 'text-skeleton'],
    a11y: {
      ariaLabel: 'Cargando...',
      role: 'status',
    },
    motionTier: 'low',
    motion: {
      shimmer: 'background-position 1.5s infinite ease-in-out',
    },
    functionalRequirements: ['duration', 'shape'],
    implementation: 'useEffect with cancelled flag pattern (cleanup on unmount)',
    testRequirements: [
      'skeleton renders during loading state',
      'real content replaces skeleton after load',
      'cancelled flag prevents state update after unmount',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'empty-state',
    name: 'Empty State',
    purpose: 'Communicate clearly when a section has no data, with a call to action',
    pattern: 'emptyState',
    allowedVerticals: ['*'],
    mobileSafe: true,
    a11y: { role: 'status' },
    motionTier: 'none',
    functionalRequirements: ['message'],
    optional: ['icon', 'cta', 'description'],
    testRequirements: [
      'empty state renders when list is empty',
      'CTA is live (not dead) if present',
    ],
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'error-state',
    name: 'Error State with Retry',
    purpose: 'Show meaningful error + retry CTA, never a blank screen',
    pattern: 'errorState',
    allowedVerticals: ['*'],
    mobileSafe: true,
    a11y: { role: 'alert', ariaLive: 'assertive' },
    motionTier: 'none',
    functionalRequirements: ['message', 'onRetry'],
    optional: ['details', 'contactLink'],
    testRequirements: [
      'error state renders with message',
      'retry button calls onRetry',
      'retry button is live (not dead)',
    ],
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'error-boundary',
    name: 'React Error Boundary',
    purpose: 'Catch React render errors and show informative fallback UI, not white screen',
    pattern: 'errorBoundary',
    allowedVerticals: ['*'],
    mobileSafe: true,
    implementation: 'Class component with getDerivedStateFromError (React 16+ compatible)',
    a11y: { role: 'alert' },
    motionTier: 'none',
    functionalRequirements: ['getDerivedStateFromError', 'render fallback'],
    fallbackContent: ['error message', 'stack trace (dev)', 'demo badge'],
    testRequirements: [
      'catches render errors without white screen',
      'shows error message in fallback',
      'does not break parent tree',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'functional-modal',
    name: 'Functional Modal',
    purpose: 'Modal dialog with focus trap, keyboard dismiss, and scroll lock',
    pattern: 'modal',
    allowedVerticals: ['*'],
    mobileSafe: true,
    a11y: {
      role: 'dialog',
      ariaModal: true,
      keyboardDismiss: 'Escape',
      focusTrap: true,
      scrollLock: false,
    },
    motionTier: 'medium',
    motion: {
      overlay: 'overlayIn .2s fade',
      modal: 'modalIn .32s spring scale',
    },
    functionalRequirements: ['onOpen', 'onClose'],
    mobileRequirements: ['max-width calc(100vw - 32px)', 'max-height calc(100vh - 40px)', 'overflow-y: auto'],
    testRequirements: [
      'escape key closes modal',
      'backdrop click closes modal',
      'close button calls onClose',
      'renders within viewport on mobile 390px',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'functional-drawer',
    name: 'Functional Drawer',
    purpose: 'Side panel drawer with slide animation, backdrop, and keyboard dismiss',
    pattern: 'drawer',
    allowedVerticals: ['*'],
    mobileSafe: true,
    variants: ['right-panel', 'left-panel', 'bottom-sheet'],
    a11y: {
      role: 'dialog',
      ariaModal: true,
      keyboardDismiss: 'Escape',
    },
    motionTier: 'medium',
    motion: {
      enter: 'translateX(100%) → translateX(0) .3s spring',
    },
    functionalRequirements: ['onClose'],
    mobileRequirements: ['full-width on 390px', 'scrollable content'],
    testRequirements: [
      'escape key closes drawer',
      'backdrop click closes drawer',
      'action buttons provide feedback before closing',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
  {
    id: 'reduced-motion-hook',
    name: 'useReducedMotion Hook',
    purpose: 'React hook that respects prefers-reduced-motion media query, correctly implemented',
    pattern: 'a11yHook',
    allowedVerticals: ['*'],
    mobileSafe: true,
    a11y: { wcag: '2.3.3 Animation from Interactions' },
    motionTier: 'none',
    implementation: 'lazy useState initializer + mq created once in useEffect (not on every render)',
    antiPattern: 'Creating new MediaQueryList in render — causes infinite effect loop',
    functionalRequirements: ['lazy-init-state', 'mq-inside-useEffect', 'removeEventListener-cleanup'],
    testRequirements: [
      'returns true when prefers-reduced-motion is reduce',
      'returns false in standard environment',
      'does not create new MediaQueryList on every render',
    ],
    pilotSource: 'fisionova-premium-v2-pilot',
    classification: 'CORE_REUSABLE',
  },
]);

export function getInteractivePatternById(id) {
  return INTERACTIVE_PATTERN_RECIPES.find(r => r.id === id) ?? null;
}

export function getInteractivePatternsByClassification(cls) {
  return INTERACTIVE_PATTERN_RECIPES.filter(r => r.classification === cls);
}

export function listInteractivePatternIds() {
  return INTERACTIVE_PATTERN_RECIPES.map(r => r.id);
}

export const INTERACTIVE_PATTERN_COUNT = INTERACTIVE_PATTERN_RECIPES.length;
