/**
 * Social Proof Section Recipes V2 — 5 variants
 */

export const SOCIAL_PROOF_RECIPES = Object.freeze([
  {
    id: 'social-proof-testimonials-grid',
    name: 'Testimonials Grid',
    description: '3-column testimonial cards with avatar, rating, quote',
    layout: '3col-grid',
    elements: ['section-header', 'testimonial-cards'],
    cardElements: ['avatar', 'name', 'role', 'company', 'rating', 'quote'],
    presets: ['friendly-human', 'clinical-premium', 'professional-authority'],
    motionSuggestion: 'Stagger cards 100ms each',
    minTestimonials: 3,
    maxTestimonials: 6,
  },
  {
    id: 'social-proof-carousel',
    name: 'Testimonials Carousel',
    description: 'Auto-advancing testimonial carousel with navigation',
    layout: 'carousel',
    elements: ['section-header', 'testimonial-carousel', 'dots-nav'],
    cardElements: ['large-quote', 'avatar', 'name', 'role', 'stars'],
    presets: ['luxury-editorial', 'minimal-premium', 'immersive-showcase'],
    motionSuggestion: 'Slide transition 400ms ease, auto-advance every 5s',
    minTestimonials: 3,
    autoAdvance: true,
  },
  {
    id: 'social-proof-logos',
    name: 'Client Logo Strip',
    description: 'Trusted-by logo bar with optional marquee scroll',
    layout: 'logo-strip',
    elements: ['trust-label', 'logo-row'],
    cardElements: ['logo-image', 'company-name'],
    presets: ['professional-authority', 'tech-futuristic', 'minimal-premium'],
    motionSuggestion: 'Logos fade in stagger, optional marquee for 8+ logos',
    minLogos: 5,
    maxLogos: 16,
    supportsMarquee: true,
  },
  {
    id: 'social-proof-metrics',
    name: 'Impact Metrics',
    description: 'Large animated numbers with labels for social proof',
    layout: 'metrics-row',
    elements: ['optional-headline', 'metric-cards'],
    cardElements: ['animated-number', 'suffix', 'label', 'icon'],
    presets: ['professional-authority', 'tech-futuristic', 'sports-dynamic', 'data-heavy-saas'],
    motionSuggestion: 'AnimatedMetric component — counts up on scroll',
    minMetrics: 3,
    maxMetrics: 5,
  },
  {
    id: 'social-proof-case-study',
    name: 'Case Study Highlights',
    description: 'Before/after case study cards with results',
    layout: 'case-study',
    elements: ['section-header', 'case-study-cards'],
    cardElements: ['company', 'challenge', 'result-metric', 'quote', 'cta'],
    presets: ['professional-authority', 'clinical-premium', 'tech-futuristic'],
    motionSuggestion: 'Reveal on scroll with stagger',
    minCases: 2,
    maxCases: 4,
  },
]);
