// CI Config Generator — ADV-02 CI/CD Automatizado
// generateCIConfig(): genera configuración GitHub Actions reutilizable.

export const CI_TARGET = Object.freeze({
  GITHUB_ACTIONS: 'GITHUB_ACTIONS',
});

/**
 * Generate a GitHub Actions workflow configuration as a YAML string.
 * options: {
 *   workingDirectory, nodeVersion, testCommand, lintCommand, buildCommand,
 *   workflowName, triggers
 * }
 */
export function generateCIConfig(options = {}, target = CI_TARGET.GITHUB_ACTIONS) {
  if (target !== CI_TARGET.GITHUB_ACTIONS) {
    return { valid: false, error: `Unsupported target: ${target}. Currently only GITHUB_ACTIONS is supported.` };
  }

  const wd      = options.workingDirectory ?? 'app/fabrica-saas';
  const node    = options.nodeVersion      ?? '20';
  const name    = options.workflowName     ?? 'Factory CI';
  const testCmd = options.testCommand      ?? `node --test fabrica-saas/generator/tests/*.test.mjs`;
  const lintCmd = options.lintCommand      ?? 'npm run lint -- --quiet';
  const buildCmd= options.buildCommand     ?? 'npm run build';

  const yaml = `# ${name} — ADV-02 CI/CD Automatizado
# Generated by ciConfigGenerator.js — reusable across Factory verticals.
# Do NOT commit real secrets here. Use GitHub Secrets or env vars.

name: ${name}

on:
  pull_request:
    branches: [main]
    paths:
      - '${wd}/**'
      - '.github/workflows/factory-ci.yml'
  push:
    branches: [main]
    paths:
      - '${wd}/**'

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret-scan:
    name: Secret Quick Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect secrets
        run: |
          # Lightweight pattern scan — blocks on sk_live_, whsec_, BEGIN PRIVATE KEY
          if grep -rn --include="*.js" --include="*.mjs" --include="*.ts" \\
            -E "(sk_live_[A-Za-z0-9]{20,}|whsec_[A-Za-z0-9]{20,}|BEGIN PRIVATE KEY)" \\
            ${wd}/ 2>/dev/null | grep -v ".test." | grep -v "fixture"; then
            echo "CRITICAL: Secret pattern detected in source files"
            exit 1
          fi
          echo "Secret scan: no critical patterns found"

  ci:
    name: Test · Lint · Build
    needs: [secret-scan]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${node}
        uses: actions/setup-node@v4
        with:
          node-version: '${node}'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run tests
        run: ${testCmd}

      - name: Lint
        run: ${lintCmd}

      - name: Build
        run: ${buildCmd}

      - name: Validate artifact
        run: |
          if [ ! -f dist/index.html ]; then
            echo "FAIL: dist/index.html not found"
            exit 1
          fi
          echo "Artifact: dist/index.html present"
          ls -la dist/

  quality-gate:
    name: Quality Gate
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "Quality gate: PASS — tests, lint, build, secret-scan all green"
`;

  return {
    valid:  true,
    target,
    yaml,
    disclaimer: 'NO_REAL_DEPLOY. Generated config is advisory. Review before applying.',
    outputPath: '.github/workflows/factory-ci.yml',
  };
}

/**
 * Generate a reusable workflow template (workflow_call).
 */
export function generateReusableWorkflow(options = {}) {
  const node    = options.nodeVersion  ?? '20';
  const wd      = options.workingDir   ?? 'app';
  const testCmd = options.testCommand  ?? `node --test fabrica-saas/generator/tests/*.test.mjs`;
  const lintCmd = options.lintCommand  ?? 'npm run lint -- --quiet';
  const buildCmd= options.buildCommand ?? 'npm run build';

  const yaml = `# Factory Reusable CI Workflow — ADV-02
# Usage: call this from other workflows via workflow_call.

name: Factory Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '${node}'
      working-directory:
        type: string
        default: '${wd}'
      test-command:
        type: string
        default: '${testCmd}'
      lint-command:
        type: string
        default: '${lintCmd}'
      build-command:
        type: string
        default: '${buildCmd}'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: \${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: \${{ inputs.node-version }}
          cache: 'npm'
      - run: npm ci --prefer-offline
      - run: \${{ inputs.test-command }}
      - run: \${{ inputs.lint-command }}
      - run: \${{ inputs.build-command }}
`;

  return { valid: true, yaml, outputPath: '.github/workflows/factory-ci-reusable.yml' };
}

export const CI_CONFIG_GENERATOR_VERSION = '1.0.0';
