// Client SOP — FASE 5: procesos del cliente/negocio a lo largo del ciclo de vida

import { createSOP, SOP_STEP_TYPES } from './sopEngine.js';

export const CLIENT_SOPS = Object.freeze({
  LEAD_INTAKE:        'CLIENT_LEAD_INTAKE',
  QUALIFICATION:      'CLIENT_QUALIFICATION',
  DISCOVERY:          'CLIENT_DISCOVERY',
  DIAGNOSIS:          'CLIENT_DIAGNOSIS',
  REQUIREMENTS:       'CLIENT_REQUIREMENTS',
  PROPOSAL_REVIEW:    'CLIENT_PROPOSAL_REVIEW',
  APPROVAL:           'CLIENT_APPROVAL',
  CHANGE_REQUEST:     'CLIENT_CHANGE_REQUEST',
  RESPONSIBILITIES:   'CLIENT_RESPONSIBILITIES',
  DELIVERY_ACCEPTANCE:'CLIENT_DELIVERY_ACCEPTANCE',
  HANDOFF:            'CLIENT_HANDOFF',
  SUPPORT_START:      'CLIENT_SUPPORT_START',
  CLOSEOUT:           'CLIENT_CLOSEOUT',
});

export const sopLeadIntake = createSOP({
  id:       CLIENT_SOPS.LEAD_INTAKE,
  title:    'Lead Intake',
  purpose:  'Capture and validate initial lead information before qualification',
  scope:    'Any inbound lead (web form, referral, direct contact)',
  owner:    'COMMERCIAL',
  participants: ['COMMERCIAL', 'CLIENT_OWNER'],
  trigger:  'New lead submits contact form or direct inquiry',
  requiredInputs: ['businessName', 'contactRole', 'mainProblems', 'location'],
  steps: [
    { label: 'Receive lead data', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Validate required fields', type: SOP_STEP_TYPES.GATE, gate: 'required_fields_complete', owner: 'COMMERCIAL' },
    { label: 'Assign commercial owner', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Log in CRM', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Send acknowledgement', type: SOP_STEP_TYPES.NOTIFICATION, owner: 'COMMERCIAL' },
    { label: 'Schedule qualification call', type: SOP_STEP_TYPES.HANDOFF, owner: 'COMMERCIAL' },
  ],
  decisionRules: ['If required fields missing → request clarification before proceeding'],
  qualityChecks: ['No duplicate leads', 'Contact info verified'],
  securityChecks: ['No real PII stored beyond minimum needed'],
  handoff: 'Qualified lead data → CLIENT_QUALIFICATION SOP',
  escalation: 'AGENCY_OWNER if lead from strategic partner',
  completionCriteria: ['Lead logged in CRM', 'Acknowledgement sent', 'Qualification scheduled'],
  artifacts: ['Lead record', 'CRM entry'],
  metrics: ['lead_to_qualification_time_hours'],
  bpmnRef: 'BPMN_AGENCY.lead_intake',
}).sop;

export const sopQualification = createSOP({
  id:       CLIENT_SOPS.QUALIFICATION,
  title:    'Lead Qualification',
  purpose:  'Determine if lead is a good fit for agency services',
  scope:    'All leads that pass intake',
  owner:    'COMMERCIAL',
  participants: ['COMMERCIAL', 'CLIENT_OWNER'],
  trigger:  'Lead intake complete',
  requiredInputs: ['budgetRange', 'desiredTimeline', 'decisionMaker', 'businessGoals', 'sector'],
  steps: [
    { label: 'Complete qualification questionnaire', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Assess budget fit', type: SOP_STEP_TYPES.DECISION, decision: 'budget_qualified', owner: 'COMMERCIAL' },
    { label: 'Assess timeline fit', type: SOP_STEP_TYPES.DECISION, decision: 'timeline_qualified', owner: 'COMMERCIAL' },
    { label: 'Confirm decision maker present', type: SOP_STEP_TYPES.GATE, gate: 'decision_maker_confirmed', owner: 'COMMERCIAL' },
    { label: 'Score qualification', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Flag HUMAN_REVIEW if risk signals', type: SOP_STEP_TYPES.DECISION, decision: 'human_review_required', owner: 'COMMERCIAL' },
    { label: 'Route: QUALIFIED → Discovery / NOT_A_FIT → close', type: SOP_STEP_TYPES.HANDOFF, owner: 'COMMERCIAL' },
  ],
  decisionRules: [
    'budget < 500 EUR → NOT_A_FIT',
    'healthData=true → HUMAN_REVIEW',
    'no decisionMaker → NEEDS_MORE_INFO',
  ],
  qualityChecks: ['Score logged', 'Reason documented'],
  securityChecks: ['No sensitive health data stored beyond flag'],
  handoff: 'Qualified lead → CLIENT_DISCOVERY SOP',
  escalation: 'AGENCY_OWNER if HUMAN_REVIEW and health/legal concerns',
  completionCriteria: ['Qualification outcome documented', 'Lead routed correctly'],
  artifacts: ['Qualification score', 'Qualification outcome'],
  metrics: ['qualification_rate', 'avg_qualification_score'],
  bpmnRef: 'BPMN_AGENCY.qualification',
}).sop;

export const sopDiscovery = createSOP({
  id:       CLIENT_SOPS.DISCOVERY,
  title:    'Discovery',
  purpose:  'Understand business context, pain points, and technical environment',
  scope:    'Qualified leads',
  owner:    'PROJECT_MANAGER',
  participants: ['PROJECT_MANAGER', 'AI_SPECIALIST', 'CLIENT_OWNER'],
  trigger:  'Lead qualification outcome = QUALIFIED or HUMAN_REVIEW (cleared)',
  requiredInputs: ['businessType', 'currentTools', 'teamSize', 'mainProblems', 'businessGoals'],
  steps: [
    { label: 'Schedule discovery session', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Conduct discovery interview', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Document pain points', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Identify current tools and integrations', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Map business goals to solutions', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Validate scope feasibility', type: SOP_STEP_TYPES.GATE, gate: 'scope_feasible', owner: 'PROJECT_MANAGER' },
    { label: 'Hand off to Diagnosis', type: SOP_STEP_TYPES.HANDOFF, owner: 'PROJECT_MANAGER' },
  ],
  qualityChecks: ['All pain points documented', 'Client goals aligned'],
  securityChecks: ['No client credentials requested in this phase'],
  handoff: 'Discovery summary → CLIENT_DIAGNOSIS SOP',
  escalation: 'AGENCY_OWNER if scope exceeds agency capability',
  completionCriteria: ['Discovery doc signed off by client', 'Feasibility confirmed'],
  artifacts: ['Discovery summary document'],
  metrics: ['discovery_session_duration_hours'],
  bpmnRef: 'BPMN_AGENCY.discovery',
}).sop;

export const sopDiagnosis = createSOP({
  id:       CLIENT_SOPS.DIAGNOSIS,
  title:    'Business Diagnosis',
  purpose:  'Run structured diagnosis to identify root problems and opportunities',
  scope:    'Post-discovery clients',
  owner:    'AI_SPECIALIST',
  participants: ['AI_SPECIALIST', 'PROJECT_MANAGER', 'CLIENT_OWNER'],
  trigger:  'Discovery complete',
  requiredInputs: ['discoverySummary', 'businessType', 'currentTools', 'teamSize'],
  steps: [
    { label: 'Run diagnostic engine', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Identify problem categories', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Score diagnosis severity', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Map to recommended solutions', type: SOP_STEP_TYPES.ACTION, owner: 'AI_SPECIALIST' },
    { label: 'Validate with client', type: SOP_STEP_TYPES.GATE, gate: 'client_validates_diagnosis', owner: 'PROJECT_MANAGER' },
    { label: 'Approve for requirements', type: SOP_STEP_TYPES.HANDOFF, owner: 'PROJECT_MANAGER' },
  ],
  qualityChecks: ['Diagnosis matches stated pain points', 'Recommendations are feasible'],
  securityChecks: ['Diagnosis output contains no real credentials'],
  handoff: 'Diagnosis report → CLIENT_REQUIREMENTS SOP',
  escalation: 'AGENCY_OWNER if diagnosis reveals compliance risk',
  completionCriteria: ['Diagnosis report generated', 'Client validates diagnosis'],
  artifacts: ['Diagnosis report'],
  metrics: ['diagnosis_accuracy_client_validation_rate'],
  bpmnRef: 'BPMN_AGENCY.diagnosis',
}).sop;

export const sopRequirements = createSOP({
  id:       CLIENT_SOPS.REQUIREMENTS,
  title:    'Requirements Definition',
  purpose:  'Define P0/P1/P2 requirements from diagnosis and client input',
  scope:    'Post-diagnosis clients',
  owner:    'PROJECT_MANAGER',
  participants: ['PROJECT_MANAGER', 'DEVELOPER', 'CLIENT_OWNER'],
  trigger:  'Diagnosis approved by client',
  requiredInputs: ['diagnosisReport', 'businessGoals', 'sector'],
  steps: [
    { label: 'Build requirements list', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Classify P0/P1/P2', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Check at least one P0 requirement', type: SOP_STEP_TYPES.GATE, gate: 'has_p0_requirements', owner: 'PROJECT_MANAGER' },
    { label: 'Validate with client', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Lock requirements', type: SOP_STEP_TYPES.GATE, gate: 'requirements_approved', owner: 'PROJECT_MANAGER' },
    { label: 'Hand off to Scope', type: SOP_STEP_TYPES.HANDOFF, owner: 'PROJECT_MANAGER' },
  ],
  qualityChecks: ['All requirements traceable to diagnosis', 'No gold-plating'],
  securityChecks: ['Legal/compliance requirements captured'],
  handoff: 'Requirements doc → Scope Builder',
  escalation: 'AGENCY_OWNER if client adds unlimited requirements',
  completionCriteria: ['Requirements signed off', 'Priority classification complete'],
  artifacts: ['Requirements document with P0/P1/P2 classification'],
  metrics: ['requirements_change_rate_post_approval'],
  bpmnRef: 'BPMN_AGENCY.requirements',
}).sop;

export const sopProposalReview = createSOP({
  id:       CLIENT_SOPS.PROPOSAL_REVIEW,
  title:    'Proposal Review',
  purpose:  'Guide client through proposal review and decision',
  scope:    'Clients receiving a commercial proposal',
  owner:    'COMMERCIAL',
  participants: ['COMMERCIAL', 'CLIENT_OWNER', 'AGENCY_OWNER'],
  trigger:  'Proposal generated and sent',
  requiredInputs: ['proposalDocument', 'clientEmail'],
  steps: [
    { label: 'Send proposal to client', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Schedule review call', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Conduct proposal walkthrough', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Address questions and objections', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Client decision: accept/negotiate/reject', type: SOP_STEP_TYPES.DECISION, decision: 'proposal_outcome', owner: 'CLIENT_OWNER' },
    { label: 'If revisions: update proposal', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL', optional: true },
    { label: 'Route to Approval or close', type: SOP_STEP_TYPES.HANDOFF, owner: 'COMMERCIAL' },
  ],
  decisionRules: ['accepted → CLIENT_APPROVAL', 'rejected → archive lead', 'negotiate → revise proposal (max 2 rounds)'],
  qualityChecks: ['Proposal revision tracked'],
  securityChecks: ['No payment data collected at this stage'],
  handoff: 'Accepted proposal → CLIENT_APPROVAL SOP',
  escalation: 'AGENCY_OWNER if discount > 20%',
  completionCriteria: ['Client decision documented', 'Revision cycle closed'],
  artifacts: ['Accepted proposal', 'Decision record'],
  metrics: ['proposal_acceptance_rate', 'avg_revision_rounds'],
  bpmnRef: 'BPMN_CLIENT.proposal_review',
}).sop;

export const sopApproval = createSOP({
  id:       CLIENT_SOPS.APPROVAL,
  title:    'Project Approval',
  purpose:  'Formal project approval before production starts',
  scope:    'All accepted proposals',
  owner:    'AGENCY_OWNER',
  participants: ['AGENCY_OWNER', 'COMMERCIAL', 'CLIENT_OWNER'],
  trigger:  'Proposal accepted by client',
  requiredInputs: ['acceptedProposal', 'scopeDocument', 'clientSignoff'],
  steps: [
    { label: 'Confirm scope document exists', type: SOP_STEP_TYPES.GATE, gate: 'scope_document_ready', owner: 'PROJECT_MANAGER' },
    { label: 'Confirm budget confirmed', type: SOP_STEP_TYPES.GATE, gate: 'budget_confirmed', owner: 'COMMERCIAL' },
    { label: 'Agency owner approval', type: SOP_STEP_TYPES.GATE, gate: 'agency_owner_approves', owner: 'AGENCY_OWNER' },
    { label: 'Generate approval record (declarative)', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL' },
    { label: 'Kick off production', type: SOP_STEP_TYPES.HANDOFF, owner: 'PROJECT_MANAGER' },
  ],
  decisionRules: ['All gates must pass before production starts'],
  qualityChecks: ['Approval record includes disclaimer: not a legal contract'],
  securityChecks: ['No payment processing at this step'],
  handoff: 'Approval record → Production pipeline',
  escalation: 'AGENCY_OWNER',
  completionCriteria: ['Approval record generated', 'Production ticket created'],
  artifacts: ['Approval record (declarative, not legal contract)'],
  metrics: ['approval_to_production_start_hours'],
  bpmnRef: 'BPMN_AGENCY.approval',
}).sop;

export const sopChangeRequest = createSOP({
  id:       CLIENT_SOPS.CHANGE_REQUEST,
  title:    'Change Request',
  purpose:  'Handle scope changes, bugs, addons during or after production',
  scope:    'Any client requesting a change after approval',
  owner:    'PROJECT_MANAGER',
  participants: ['PROJECT_MANAGER', 'CLIENT_OWNER', 'AGENCY_OWNER'],
  trigger:  'Client or internal team identifies a change need',
  requiredInputs: ['changeDescription', 'changeType', 'requestedBy'],
  steps: [
    { label: 'Classify change type (BUG/MINOR/ADDON/SCOPE_CHANGE/URGENT/NEW_REQUIREMENT)', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Estimate impact and cost', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Check if approval required', type: SOP_STEP_TYPES.DECISION, decision: 'approval_required', owner: 'PROJECT_MANAGER' },
    { label: 'Get agency owner approval if SCOPE_CHANGE/NEW_REQUIREMENT', type: SOP_STEP_TYPES.GATE, gate: 'scope_change_approved', owner: 'AGENCY_OWNER', optional: true },
    { label: 'Implement or defer', type: SOP_STEP_TYPES.ACTION, owner: 'DEVELOPER' },
    { label: 'QA the change', type: SOP_STEP_TYPES.GATE, gate: 'change_qa_pass', owner: 'QA' },
    { label: 'Communicate to client', type: SOP_STEP_TYPES.NOTIFICATION, owner: 'PROJECT_MANAGER' },
  ],
  decisionRules: [
    'BUG → no approval, implement in support window',
    'SCOPE_CHANGE on ESSENTIAL tier → flag PRO upgrade',
    'NEW_REQUIREMENT → always new contract',
  ],
  qualityChecks: ['Change logged in CR system', 'Impact documented'],
  securityChecks: ['New feature does not introduce security regression'],
  handoff: 'Resolved CR → update tracking',
  escalation: 'AGENCY_OWNER if CR leads to major scope expansion',
  completionCriteria: ['CR status = DONE or DEFERRED', 'Client notified'],
  artifacts: ['Change Request record'],
  metrics: ['cr_resolution_time_days', 'cr_approval_rate'],
  bpmnRef: 'BPMN_AGENCY.change_request',
}).sop;

export const sopDeliveryAcceptance = createSOP({
  id:       CLIENT_SOPS.DELIVERY_ACCEPTANCE,
  title:    'Delivery Acceptance',
  purpose:  'Client acceptance of delivered product before handoff',
  scope:    'All deliveries',
  owner:    'PROJECT_MANAGER',
  participants: ['PROJECT_MANAGER', 'QA', 'CLIENT_OWNER'],
  trigger:  'Delivery readiness gate passes',
  requiredInputs: ['deliveryManifest', 'qaReport'],
  steps: [
    { label: 'Present delivery manifest to client', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Demo product to client', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Client reviews acceptance checklist', type: SOP_STEP_TYPES.ACTION, owner: 'CLIENT_OWNER' },
    { label: 'Client accepts product', type: SOP_STEP_TYPES.GATE, gate: 'client_accepts', owner: 'CLIENT_OWNER' },
    { label: 'Document deferred items if any', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER', optional: true },
    { label: 'Hand off to Handoff SOP', type: SOP_STEP_TYPES.HANDOFF, owner: 'PROJECT_MANAGER' },
  ],
  decisionRules: ['client rejects → open CR or rework', 'client accepts with notes → CLOSED_WITH_DEFERRED_ITEMS'],
  qualityChecks: ['Acceptance checklist complete', 'Known limitations documented'],
  securityChecks: ['No secrets in delivery manifest'],
  handoff: 'Acceptance record → CLIENT_HANDOFF SOP',
  escalation: 'AGENCY_OWNER if client refuses to accept without justification',
  completionCriteria: ['Acceptance documented', 'Client signature on checklist'],
  artifacts: ['Delivery acceptance record'],
  metrics: ['delivery_acceptance_first_pass_rate'],
  bpmnRef: 'BPMN_CLIENT.delivery_acceptance',
}).sop;

export const sopHandoff = createSOP({
  id:       CLIENT_SOPS.HANDOFF,
  title:    'Client Handoff',
  purpose:  'Transfer product ownership to client with training and documentation',
  scope:    'All accepted deliveries',
  owner:    'PROJECT_MANAGER',
  participants: ['PROJECT_MANAGER', 'DEVELOPER', 'CLIENT_OWNER', 'CLIENT_USER'],
  trigger:  'Delivery accepted by client',
  requiredInputs: ['deliveryManifest', 'acceptanceRecord'],
  steps: [
    { label: 'Conduct admin panel training', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Review booking/CRM workflows', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Explain notification setup', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Walk through Make/automation dashboard', type: SOP_STEP_TYPES.ACTION, owner: 'AUTOMATION_SPECIALIST' },
    { label: 'Complete training checklist', type: SOP_STEP_TYPES.GATE, gate: 'training_complete', owner: 'CLIENT_OWNER' },
    { label: 'Transfer credential plan (no real secrets)', type: SOP_STEP_TYPES.ACTION, owner: 'DEVELOPER' },
    { label: 'Complete acceptance checklist', type: SOP_STEP_TYPES.GATE, gate: 'acceptance_complete', owner: 'CLIENT_OWNER' },
    { label: 'Open support window', type: SOP_STEP_TYPES.HANDOFF, owner: 'SUPPORT' },
  ],
  decisionRules: ['All training items must be marked done before handoff is complete'],
  qualityChecks: ['Training checklist 7/7', 'Acceptance checklist 6/6'],
  securityChecks: ['Agency does not retain client production credentials'],
  handoff: 'Handoff complete → CLIENT_SUPPORT_START SOP',
  escalation: 'PROJECT_MANAGER if client refuses training',
  completionCriteria: ['handoffComplete=true', 'Support window open'],
  artifacts: ['Handoff record', 'Credential plan (no secrets)'],
  metrics: ['training_completion_time_hours'],
  bpmnRef: 'BPMN_CLIENT.handoff',
}).sop;

export const sopSupportStart = createSOP({
  id:       CLIENT_SOPS.SUPPORT_START,
  title:    'Support Window Start',
  purpose:  'Initialize client support window after handoff',
  scope:    'All delivered clients',
  owner:    'SUPPORT',
  participants: ['SUPPORT', 'CLIENT_OWNER', 'PROJECT_MANAGER'],
  trigger:  'Handoff complete',
  requiredInputs: ['tier', 'deliveryDate', 'clientContact'],
  steps: [
    { label: 'Create support window record', type: SOP_STEP_TYPES.ACTION, owner: 'SUPPORT' },
    { label: 'Communicate support channels to client', type: SOP_STEP_TYPES.NOTIFICATION, owner: 'SUPPORT' },
    { label: 'Explain covered vs not-covered tickets', type: SOP_STEP_TYPES.ACTION, owner: 'SUPPORT' },
    { label: 'Set ticket intake open', type: SOP_STEP_TYPES.ACTION, owner: 'SUPPORT' },
    { label: 'Monitor for first 48h', type: SOP_STEP_TYPES.ACTION, owner: 'SUPPORT' },
  ],
  qualityChecks: ['Support duration correct per tier (ESSENTIAL=7d, PRO=14d, PREMIUM=30d)'],
  securityChecks: ['Support access limited to bug/config — no scope changes'],
  handoff: 'Support window → CLIENT_CLOSEOUT SOP (at expiry)',
  escalation: 'PROJECT_MANAGER if SEV1/SEV2 incident during support window',
  completionCriteria: ['Support window active', 'Client has support contact'],
  artifacts: ['Support window record'],
  metrics: ['first_response_time_hours', 'ticket_resolution_rate'],
  bpmnRef: 'BPMN_AGENCY.support',
}).sop;

export const sopCloseout = createSOP({
  id:       CLIENT_SOPS.CLOSEOUT,
  title:    'Client Closeout',
  purpose:  'Formally close client project after support window',
  scope:    'All clients post-support',
  owner:    'AGENCY_OWNER',
  participants: ['AGENCY_OWNER', 'PROJECT_MANAGER', 'SUPPORT'],
  trigger:  'Support window expires or all deliverables confirmed',
  requiredInputs: ['deliveryManifest', 'handoffRecord', 'supportWindowRecord'],
  steps: [
    { label: 'Verify delivery manifest exists', type: SOP_STEP_TYPES.GATE, gate: 'manifest_exists', owner: 'PROJECT_MANAGER' },
    { label: 'Verify handoff complete', type: SOP_STEP_TYPES.GATE, gate: 'handoff_complete', owner: 'PROJECT_MANAGER' },
    { label: 'Check no critical open CRs', type: SOP_STEP_TYPES.GATE, gate: 'no_critical_open_crs', owner: 'PROJECT_MANAGER' },
    { label: 'Generate closeout record', type: SOP_STEP_TYPES.ACTION, owner: 'AGENCY_OWNER' },
    { label: 'Archive project', type: SOP_STEP_TYPES.ACTION, owner: 'PROJECT_MANAGER' },
    { label: 'Request client testimonial (optional)', type: SOP_STEP_TYPES.ACTION, owner: 'COMMERCIAL', optional: true },
  ],
  decisionRules: ['CLOSED_WITH_DEFERRED_ITEMS allowed if only non-critical deferred'],
  qualityChecks: ['Closeout record includes declarative disclaimer'],
  securityChecks: ['All agency access to client systems revoked'],
  handoff: 'Closed project → historical record',
  escalation: 'AGENCY_OWNER if client disputes closeout',
  completionCriteria: ['closeoutType=CLIENT_CLOSEOUT', 'status=CLOSED or CLOSED_WITH_DEFERRED_ITEMS'],
  artifacts: ['Client closeout record (declarative, not a legal contract)'],
  metrics: ['client_lifetime_value', 'nps_score'],
  bpmnRef: 'BPMN_CLIENT.closeout',
}).sop;

export const ALL_CLIENT_SOPS = [
  sopLeadIntake, sopQualification, sopDiscovery, sopDiagnosis,
  sopRequirements, sopProposalReview, sopApproval, sopChangeRequest,
  sopDeliveryAcceptance, sopHandoff, sopSupportStart, sopCloseout,
];
