// Browser QA Report — ADV-06
// Generates structured QA reports from phase results and scores.

export const REPORT_FORMAT = Object.freeze({
  JSON:     'JSON',
  MARKDOWN: 'MARKDOWN',
  SUMMARY:  'SUMMARY',
});

export const REPORT_STATUS = Object.freeze({
  PASS:    'PASS',
  WARN:    'WARN',
  FAIL:    'FAIL',
  PARTIAL: 'PARTIAL',
});

export function createQAReport(params = {}) {
  const {
    appId, appName, qaScore = {}, phaseResults = {},
    flows = [], duration = 0, timestamp = null,
  } = params;
  if (!appId)   return { valid: false, error: 'appId required' };
  if (!appName) return { valid: false, error: 'appName required' };

  const failedPhases = Object.entries(phaseResults)
    .filter(([, r]) => r?.status === 'FAIL')
    .map(([phase]) => phase);
  const warnPhases = Object.entries(phaseResults)
    .filter(([, r]) => r?.status === 'WARN')
    .map(([phase]) => phase);

  const status = failedPhases.length > 0                      ? REPORT_STATUS.FAIL
    : warnPhases.length > 3                                    ? REPORT_STATUS.WARN
    : Object.keys(phaseResults).length < 5                     ? REPORT_STATUS.PARTIAL
    : REPORT_STATUS.PASS;

  return Object.freeze({
    valid:       true,
    reportId:    `QA-RPT-${appId}-${Date.now()}`,
    appId,
    appName,
    timestamp:   timestamp ?? new Date().toISOString(),
    status,
    score:       qaScore.score ?? null,
    grade:       qaScore.grade ?? null,
    phaseCount:  Object.keys(phaseResults).length,
    failedPhases,
    warnPhases,
    flowResults: flows,
    duration,
    isReal:      false,
  });
}

export function formatReportMarkdown(report = {}) {
  if (!report.valid) return '# QA Report — ERROR\n\nInvalid report data.';

  const statusEmoji = { PASS: '✅', WARN: '⚠️', FAIL: '❌', PARTIAL: '🔶' };
  const emoji = statusEmoji[report.status] ?? '❓';

  const lines = [
    `# Browser QA Report — ${report.appName}`,
    ``,
    `**Status:** ${emoji} ${report.status}`,
    `**Score:** ${report.score ?? 'N/A'}/100 (Grade ${report.grade ?? 'N/A'})`,
    `**Date:** ${report.timestamp}`,
    `**Phases evaluated:** ${report.phaseCount}`,
    ``,
  ];

  if (report.failedPhases.length > 0) {
    lines.push(`## ❌ Failed Phases`);
    report.failedPhases.forEach(p => lines.push(`- ${p}`));
    lines.push('');
  }
  if (report.warnPhases.length > 0) {
    lines.push(`## ⚠️ Warning Phases`);
    report.warnPhases.forEach(p => lines.push(`- ${p}`));
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by ADV-06 Browser QA Engine. isReal: false*`);

  return lines.join('\n');
}

export function formatReportSummary(report = {}) {
  if (!report.valid) return 'QA report error';
  return `[${report.appName}] ${report.status} | Score: ${report.score ?? '?'}/100 | `
    + `${report.failedPhases.length} failed, ${report.warnPhases.length} warned | `
    + `${report.phaseCount} phases`;
}

export const BROWSER_QA_REPORT_VERSION = '1.0.0';
