// CI/CD Bridge — ADV-06
// Connects browser QA results to the ADV-02 CI/CD pipeline.

export const CI_QA_TRIGGER = Object.freeze({
  PR_OPEN:        'PR_OPEN',
  PR_MERGE:       'PR_MERGE',
  DEPLOY_STAGING: 'DEPLOY_STAGING',
  SCHEDULE:       'SCHEDULE',
  MANUAL:         'MANUAL',
});

export const CI_QA_STATUS = Object.freeze({
  PASS:    'PASS',
  FAIL:    'FAIL',
  PENDING: 'PENDING',
  SKIPPED: 'SKIPPED',
});

export const BROWSER_QA_CI_JOB = Object.freeze({
  SMOKE:       'browser-qa-smoke',
  FULL:        'browser-qa-full',
  RESPONSIVE:  'browser-qa-responsive',
  A11Y:        'browser-qa-a11y',
  PERFORMANCE: 'browser-qa-performance',
});

export function createCIQAConfig(params = {}) {
  const { trigger = CI_QA_TRIGGER.PR_MERGE, jobs = [BROWSER_QA_CI_JOB.SMOKE, BROWSER_QA_CI_JOB.FULL], timeout = 300 } = params;
  if (!CI_QA_TRIGGER[trigger]) return { valid: false, error: `unknown trigger: ${trigger}` };

  return Object.freeze({
    valid:    true,
    trigger,
    jobs,
    timeout,
    parallel: true,
    failFast: true,
    isReal:   false,
  });
}

export function buildCIStatusReport(jobResults = []) {
  if (!Array.isArray(jobResults)) return { valid: false, error: 'array required' };

  const failed  = jobResults.filter(j => j.status === CI_QA_STATUS.FAIL);
  const passed  = jobResults.filter(j => j.status === CI_QA_STATUS.PASS);
  const skipped = jobResults.filter(j => j.status === CI_QA_STATUS.SKIPPED);

  const overall = failed.length > 0    ? CI_QA_STATUS.FAIL
    : passed.length === 0              ? CI_QA_STATUS.PENDING
    : CI_QA_STATUS.PASS;

  return Object.freeze({
    valid:   true,
    overall,
    total:   jobResults.length,
    passed:  passed.length,
    failed:  failed.length,
    skipped: skipped.length,
    results: jobResults,
    blocksDeployment: failed.length > 0,
    isReal:  false,
  });
}

export function generateCIYamlSpec(config = {}) {
  if (!config.valid) return { valid: false, error: 'invalid config' };
  const jobLines = config.jobs.map(j => `    - name: ${j}\n      run: npx playwright test --project=${j}`).join('\n');
  const yaml = `# Auto-generated by ADV-06 CI/CD Bridge\nbrowser-qa:\n  trigger: ${config.trigger}\n  jobs:\n${jobLines}\n  timeout: ${config.timeout}\n`;
  return { valid: true, yaml, isReal: false };
}

export function selectCIJobsForDiff(changedFiles = []) {
  const hasReact = changedFiles.some(f => f.endsWith('.jsx') || f.endsWith('.tsx'));
  const hasStyle = changedFiles.some(f => f.endsWith('.css') || f.endsWith('.scss'));
  const hasRoute = changedFiles.some(f => f.includes('router') || f.includes('routes'));

  const jobs = [BROWSER_QA_CI_JOB.SMOKE];
  if (hasReact || hasRoute) jobs.push(BROWSER_QA_CI_JOB.FULL);
  if (hasStyle)             jobs.push(BROWSER_QA_CI_JOB.RESPONSIVE);

  return Object.freeze({
    valid:    true,
    jobs,
    reason:   `Selected ${jobs.length} CI jobs for ${changedFiles.length} changed files`,
    isReal:   false,
  });
}

export const CICD_BRIDGE_VERSION = '1.0.0';
