name = "cp04-reservas-proxy"
main = "src/index.js"
compatibility_date = "2026-06-10"

[vars]
ALLOWED_ORIGIN = "https://club-padel-04.pages.dev,http://localhost:5173"
AIRTABLE_BASE_ID = "appyWvzZJLzy0E6aX"
AIRTABLE_TABLE_ID = "tblBtLjPS3sis28nz"

# Secrets:
# MAKE_RESERVAS_WEBHOOK
# AIRTABLE_TOKEN

AIRTABLE_RESERVAS_TABLE="tblBtLjPS3sis28nz"

[[kv_namespaces]]
binding = "STRIPE_IDEMPOTENCY_KV"
id = "5479e1741d0b4567bb4ee075efe21303"
preview_id = "029b31a07f9f40b8925c5d64e11a9b50"
