// Maintenance Report — PASO F
// Generates structured maintenance cycle reports.

export const REPORT_SECTIONS = Object.freeze([
  'EXECUTIVE_SUMMARY',
  'CHECKLIST_RESULTS',
  'BACKUP_STATUS',
  'SECURITY_REVIEW',
  'AUTOMATION_HEALTH',
  'AI_HEALTH',
  'OPEN_TICKETS',
  'ACTIONS_REQUIRED',
  'NEXT_CYCLE',
]);

/**
 * Generate a maintenance report from a completed cycle.
 */
export function generateMaintenanceReport(cycle = {}) {
  if (!cycle || !cycle.cycleId) {
    return { valid: false, error: 'cycle with cycleId required' };
  }

  const executiveSummary = buildExecutiveSummary(cycle);
  const actionsRequired  = buildActionsRequired(cycle);
  const nextCycle        = buildNextCycleRecommendation(cycle);

  const report = {
    reportId:    `RPT-${cycle.cycleId}`,
    cycleId:     cycle.cycleId,
    clientId:    cycle.clientId,
    generatedAt: new Date().toISOString(),
    period:      {
      from: cycle.startedAt,
      to:   cycle.completedAt ?? new Date().toISOString(),
    },
    maintenanceTier:  cycle.maintenanceTier,
    overallStatus:    cycle.status,
    healthScore:      cycle.healthScore,
    healthLabel:      cycle.healthLabel,

    sections: {
      executiveSummary,
      checklistResults:  summarizeChecklist(cycle.checklist),
      backupStatus:      summarizeBackup(cycle.backupAudit, cycle.restoreReadiness),
      securityReview:    summarizeSecurity(cycle.securityAudit),
      automationHealth:  summarizeAutomation(cycle.automationAudit),
      aiHealth:          summarizeAI(cycle.aiAudit),
      actionsRequired,
      nextCycle,
    },

    disclaimer: [
      'This report is an operational record generated by the Agency AI Factory.',
      'It is not a security audit, compliance certificate, or legally binding document.',
      'No real system changes, backups, or deployments were performed.',
    ].join(' '),
  };

  return { valid: true, report };
}

function buildExecutiveSummary(cycle) {
  const icon = cycle.status === 'HEALTHY' ? '✓' : cycle.status === 'CRITICAL' ? '⚠' : '~';
  return {
    status:      cycle.status,
    healthScore: cycle.healthScore,
    healthLabel: cycle.healthLabel,
    headline:    `${icon} Maintenance cycle ${cycle.cycleId} completed — ${cycle.status}`,
    highlights: [
      `Checklist: ${cycle.checklist?.score ?? 0}/100`,
      `Security: ${cycle.securityAudit?.healthScore ?? 'N/A'}/100`,
      `Backup: ${cycle.backupAudit?.healthScore ?? 'N/A'}/100`,
      `Automations: ${cycle.automationAudit?.healthScore ?? 'N/A'}/100`,
      `AI Agents: ${cycle.aiAudit?.healthScore ?? 'N/A'}/100`,
    ],
    criticalIssues: cycle.criticalIssues ?? 0,
    warnings:       cycle.warningCount   ?? 0,
  };
}

function summarizeChecklist(checklist) {
  if (!checklist) return { available: false };
  return {
    score:          checklist.score,
    overallStatus:  checklist.overallStatus,
    passed:         checklist.passed,
    failed:         checklist.failed,
    warnings:       checklist.warnings,
    pending:        checklist.pending,
    criticalFailed: checklist.criticalFailed,
  };
}

function summarizeBackup(backupAudit, restoreReadiness) {
  return {
    healthScore:   backupAudit?.healthScore ?? null,
    status:        backupAudit?.status ?? 'UNKNOWN',
    issueCount:    backupAudit?.issues?.length ?? 0,
    restoreReady:  restoreReadiness?.restoreReady ?? false,
    rpo:           restoreReadiness?.rpo ?? null,
    rto:           restoreReadiness?.rto ?? null,
    blockers:      restoreReadiness?.blockers ?? [],
  };
}

function summarizeSecurity(securityAudit) {
  if (!securityAudit) return { available: false };
  return {
    healthScore:       securityAudit.healthScore,
    status:            securityAudit.status,
    criticalFailed:    securityAudit.criticalFailed,
    criticalFailedIds: securityAudit.criticalFailedIds ?? [],
    totalFailed:       securityAudit.failed,
  };
}

function summarizeAutomation(automationAudit) {
  if (!automationAudit) return { available: false };
  return {
    total:       automationAudit.total,
    active:      automationAudit.active,
    errored:     automationAudit.errored,
    healthScore: automationAudit.healthScore,
    status:      automationAudit.status,
  };
}

function summarizeAI(aiAudit) {
  if (!aiAudit) return { available: false };
  return {
    total:       aiAudit.total,
    healthy:     aiAudit.healthy,
    unavailable: aiAudit.unavailable,
    healthScore: aiAudit.healthScore,
    status:      aiAudit.status,
  };
}

function buildActionsRequired(cycle) {
  const actions = [];

  if ((cycle.checklist?.criticalFailed ?? 0) > 0) {
    actions.push({ priority: 'P1', action: 'Resolve critical checklist failures immediately', owner: 'AGENCY' });
  }
  if ((cycle.securityAudit?.criticalFailed ?? 0) > 0) {
    actions.push({ priority: 'P1', action: 'Remediate critical security findings', owner: 'AGENCY' });
  }
  if (cycle.backupAudit?.status === 'CRITICAL') {
    actions.push({ priority: 'P1', action: 'Restore backup operations to healthy state', owner: 'AGENCY' });
  }
  if ((cycle.automationAudit?.errored ?? 0) > 0) {
    actions.push({ priority: 'P2', action: `Fix ${cycle.automationAudit.errored} errored automation scenario(s)`, owner: 'DEVELOPER' });
  }
  if ((cycle.aiAudit?.unavailable ?? 0) > 0) {
    actions.push({ priority: 'P2', action: `Restore ${cycle.aiAudit.unavailable} unavailable AI agent(s)`, owner: 'AI_SPECIALIST' });
  }

  return {
    total:   actions.length,
    p1Count: actions.filter(a => a.priority === 'P1').length,
    p2Count: actions.filter(a => a.priority === 'P2').length,
    items:   actions,
  };
}

function buildNextCycleRecommendation(cycle) {
  const cadence = cycle.maintenanceTier === 'PRIORITY' ? 'WEEKLY'
    : cycle.maintenanceTier === 'PRO'                  ? 'BIWEEKLY'
    : 'MONTHLY';

  return {
    recommendedCadence: cadence,
    focus: (cycle.healthScore ?? 100) < 60
      ? 'Focus on resolving critical findings before full cycle'
      : 'Standard maintenance cycle',
  };
}

export const MAINTENANCE_REPORT_VERSION = '1.0.0';
