/**
 * VERTICAL · Estética · Mock data
 * Datos ficticios para demo interna. No son datos reales.
 * Emails: @demo.ficticio  ·  Teléfonos: 600 000 02x (serie reservada)
 */

export const MOCK_CLIENTES_ESTETICA = [
  {
    id: 'cle001',
    nombre: 'Sofía Ruiz (ficticia)',
    email: 'sofia.r@demo.ficticio',
    telefono: '600 000 021',
    tratamiento_interes: 'Depilación láser piernas',
    sesiones_completadas: 3,
    sesiones_restantes: 3,
    pack_contratado: 'Pack 6 sesiones',
    estado: 'en_tratamiento',
    ultima_sesion: '2026-08-15 (ficticio)',
    proxima_sesion: '2026-09-05 (ficticio)',
    origen: 'Instagram (ficticio)',
  },
  {
    id: 'cle002',
    nombre: 'Laura Martín (ficticia)',
    email: 'laura.m@demo.ficticio',
    telefono: '600 000 022',
    tratamiento_interes: 'Tratamiento facial antiedad',
    sesiones_completadas: 0,
    sesiones_restantes: 3,
    pack_contratado: 'Pack 3 sesiones',
    estado: 'cita_agendada',
    ultima_sesion: null,
    proxima_sesion: '2026-08-30 (ficticio)',
    origen: 'Web (ficticio)',
  },
  {
    id: 'cle003',
    nombre: 'Carmen Sánchez (ficticia)',
    email: 'carmen.s@demo.ficticio',
    telefono: '600 000 023',
    tratamiento_interes: 'Lifting sin cirugía (HIFU)',
    sesiones_completadas: 1,
    sesiones_restantes: 0,
    pack_contratado: 'Sesión individual',
    estado: 'completado',
    ultima_sesion: '2026-08-20 (ficticio)',
    proxima_sesion: null,
    origen: 'Referido (ficticio)',
  },
  {
    id: 'cle004',
    nombre: 'Ana Fernández (ficticia)',
    email: 'ana.f@demo.ficticio',
    telefono: '600 000 024',
    tratamiento_interes: 'Reducción corporal',
    sesiones_completadas: 0,
    sesiones_restantes: 0,
    pack_contratado: null,
    estado: 'nuevo',
    ultima_sesion: null,
    proxima_sesion: null,
    origen: 'Campaña Vuelta al verano (ficticio)',
  },
  {
    id: 'cle005',
    nombre: 'Isabel González (ficticia)',
    email: 'isabel.g@demo.ficticio',
    telefono: '600 000 025',
    tratamiento_interes: 'Tratamiento manchas solares',
    sesiones_completadas: 0,
    sesiones_restantes: 0,
    pack_contratado: null,
    estado: 'perdido',
    ultima_sesion: null,
    proxima_sesion: null,
    origen: 'Google Ads (ficticio)',
  },
];

export const MOCK_METRICAS_ESTETICA = {
  consultas_mes: 44,
  precalificadas_pct: 68,
  con_cita_pct: 42,
  oportunidades_recuperadas: 7,
  valor_pipeline: '21.400 € (ficticio)',
  tasa_conversion_consulta: 55,
  ingresos_packs_mes: '8.200 € (ficticio)',
  sesiones_realizadas_mes: 62,
  nps_estimado: 78,
  por_origen: [
    { fuente: 'Instagram', leads: 18 },
    { fuente: 'Web',       leads: 12 },
    { fuente: 'Referidos', leads: 8  },
    { fuente: 'Campañas',  leads: 6  },
  ],
  por_tratamiento: [
    { tratamiento: 'Depilación láser', leads: 20 },
    { tratamiento: 'Facial',           leads: 14 },
    { tratamiento: 'Corporal',         leads: 7  },
    { tratamiento: 'HIFU',             leads: 3  },
  ],
  por_centro: [
    { centro: 'Principal',   sesiones: 42 },
    { centro: 'Salon Norte', sesiones: 20 },
  ],
};

export const MOCK_LEADS_ABANDONO_ESTETICA = [
  {
    id: 'lab001',
    nombre: 'Pilar Torres (ficticia)',
    email: 'pilar.t@demo.ficticio',
    telefono: '600 000 026',
    tratamiento: 'Depilación láser ingles',
    estado_abandono: 'consulto_precio',
    dias_inactivo: 5,
    accion_sugerida: 'Enviar oferta Pack Bienvenida',
    estado: 'en_proceso',
  },
  {
    id: 'lab002',
    nombre: 'Rosa Jiménez (ficticia)',
    email: 'rosa.j@demo.ficticio',
    telefono: '600 000 027',
    tratamiento: 'Tratamiento facial',
    estado_abandono: 'no_confirmo_cita',
    dias_inactivo: 3,
    accion_sugerida: 'Recordatorio con slot libre mañana',
    estado: 'en_proceso',
  },
  {
    id: 'lab003',
    nombre: 'Nuria Castillo (ficticia)',
    email: 'nuria.c@demo.ficticio',
    telefono: '600 000 028',
    tratamiento: 'Reducción corporal',
    estado_abandono: 'abandono_formulario',
    dias_inactivo: 8,
    accion_sugerida: 'Campaña Mes del facial como gancho alternativo',
    estado: 'recuperado',
  },
];

export const MOCK_SLOTS_ESTETICA = [
  {
    id: 'ese001',
    fecha: '2026-09-02 (ficticio)',
    hora: '10:30',
    centro: 'Centro Principal (ficticio)',
    profesional: 'Ana García (ficticia)',
    tratamiento: 'Tratamiento facial',
    disponible: true,
  },
  {
    id: 'ese002',
    fecha: '2026-09-03 (ficticio)',
    hora: '16:00',
    centro: 'Centro Principal (ficticio)',
    profesional: 'María López (ficticia)',
    tratamiento: 'Depilación láser',
    disponible: true,
  },
  {
    id: 'ese003',
    fecha: '2026-09-06 (ficticio)',
    hora: '11:00',
    centro: 'Salón Norte (ficticio)',
    profesional: 'Ana García (ficticia)',
    tratamiento: 'Reducción corporal',
    disponible: true,
  },
];

export const MOCK_SEGUIMIENTO_ESTETICA = [
  {
    id: 'seg001',
    cliente: 'Sofía Ruiz (ficticia)',
    tratamiento: 'Depilación láser piernas',
    sesion_num: 3,
    fecha: '2026-08-15 (ficticio)',
    observaciones: 'Respuesta excelente. Reducción visible 70% (ficticio).',
    profesional: 'María López (ficticia)',
    proxima_sesion: '2026-09-05 (ficticio)',
  },
  {
    id: 'seg002',
    cliente: 'Laura Martín (ficticia)',
    tratamiento: 'Facial antiedad',
    sesion_num: 0,
    fecha: null,
    observaciones: 'Primera sesión pendiente (ficticio).',
    profesional: 'Ana García (ficticia)',
    proxima_sesion: '2026-08-30 (ficticio)',
  },
];
