// Voice Personality By Business — ADV-11

import { VOICE_PERSONALITY, SPEAKING_STYLE, FORMALITY } from './voiceAgentProfile.js';

export const BUSINESS_VERTICAL = Object.freeze({
  PADEL_CLUB:   'PADEL_CLUB',
  DENTAL_CLINIC:'DENTAL_CLINIC',
  GYM:          'GYM',
  LEGAL:        'LEGAL',
  REAL_ESTATE:  'REAL_ESTATE',
  RESTAURANT:   'RESTAURANT',
  EDUCATION:    'EDUCATION',
  PHYSIO:       'PHYSIO',
  GENERAL:      'GENERAL',
});

const VERTICAL_PERSONALITY = Object.freeze({
  [BUSINESS_VERTICAL.PADEL_CLUB]:    { personality: VOICE_PERSONALITY.FRIENDLY_ENERGETIC, style: SPEAKING_STYLE.CONVERSATIONAL, formality: FORMALITY.INFORMAL },
  [BUSINESS_VERTICAL.DENTAL_CLINIC]: { personality: VOICE_PERSONALITY.EMPATHETIC,         style: SPEAKING_STYLE.SUPPORTIVE,     formality: FORMALITY.FORMAL },
  [BUSINESS_VERTICAL.GYM]:           { personality: VOICE_PERSONALITY.FRIENDLY_ENERGETIC,  style: SPEAKING_STYLE.CONVERSATIONAL, formality: FORMALITY.INFORMAL },
  [BUSINESS_VERTICAL.LEGAL]:         { personality: VOICE_PERSONALITY.CALM_PRECISE,        style: SPEAKING_STYLE.CONSULTIVE,     formality: FORMALITY.FORMAL },
  [BUSINESS_VERTICAL.REAL_ESTATE]:   { personality: VOICE_PERSONALITY.WARM_PROFESSIONAL,   style: SPEAKING_STYLE.CONSULTIVE,     formality: FORMALITY.NEUTRAL },
  [BUSINESS_VERTICAL.RESTAURANT]:    { personality: VOICE_PERSONALITY.FRIENDLY_ENERGETIC,  style: SPEAKING_STYLE.CONVERSATIONAL, formality: FORMALITY.INFORMAL },
  [BUSINESS_VERTICAL.EDUCATION]:     { personality: VOICE_PERSONALITY.EMPATHETIC,          style: SPEAKING_STYLE.SUPPORTIVE,     formality: FORMALITY.NEUTRAL },
  [BUSINESS_VERTICAL.PHYSIO]:        { personality: VOICE_PERSONALITY.EMPATHETIC,          style: SPEAKING_STYLE.SUPPORTIVE,     formality: FORMALITY.NEUTRAL },
  [BUSINESS_VERTICAL.GENERAL]:       { personality: VOICE_PERSONALITY.WARM_PROFESSIONAL,   style: SPEAKING_STYLE.CONVERSATIONAL, formality: FORMALITY.NEUTRAL },
});

export function getPersonalityForVertical(vertical = BUSINESS_VERTICAL.GENERAL) {
  return Object.freeze({ ...(VERTICAL_PERSONALITY[vertical] ?? VERTICAL_PERSONALITY[BUSINESS_VERTICAL.GENERAL]), isReal: false });
}

export const VOICE_PERSONALITY_BY_BUSINESS_VERSION = '1.0.0';
