// BPMN Agency — FASE 19: flujo principal de la agencia

import {
  createBPMNProcess, startEvent, endEvent, task,
  xorGateway, flow,
} from './bpmnEngine.js';

const elements = [
  startEvent('start_lead', 'Lead recibido'),
  task('task_lead_intake', 'Lead Intake', 'COMMERCIAL'),
  xorGateway('gw_lead_valid', '¿Lead válido?', ['si → qualification', 'no → close']),
  task('task_qualification', 'Qualificación', 'COMMERCIAL'),
  xorGateway('gw_qualified', '¿Qualificado?', ['QUALIFIED/HUMAN_REVIEW → discovery', 'NOT_A_FIT → end_not_fit']),
  task('task_discovery', 'Discovery', 'PROJECT_MANAGER'),
  task('task_diagnosis', 'Diagnóstico', 'AI_SPECIALIST'),
  task('task_requirements', 'Requisitos', 'PROJECT_MANAGER'),
  task('task_commercial', 'Propuesta comercial', 'COMMERCIAL'),
  xorGateway('gw_proposal', '¿Propuesta aceptada?', ['si → approval', 'no → end_rejected', 'revisar → commercial']),
  task('task_scope', 'Scope', 'PROJECT_MANAGER'),
  task('task_approval', 'Aprobación', 'AGENCY_OWNER'),
  xorGateway('gw_approved', '¿Aprobado?', ['si → production', 'no → end_rejected']),
  task('task_production', 'Producción Factory', 'DEVELOPER'),
  task('task_qa', 'QA', 'QA'),
  xorGateway('gw_qa_pass', '¿QA pass?', ['si → security', 'no → production']),
  task('task_security', 'Security Review', 'QA'),
  xorGateway('gw_security_pass', '¿Security pass?', ['si → delivery', 'no → production']),
  task('task_delivery', 'Entrega', 'PROJECT_MANAGER'),
  xorGateway('gw_client_accepts', '¿Cliente acepta?', ['si → handoff', 'no → change_request']),
  task('task_change_request', 'Change Request', 'PROJECT_MANAGER'),
  task('task_handoff', 'Handoff', 'PROJECT_MANAGER'),
  task('task_support', 'Soporte', 'SUPPORT'),
  xorGateway('gw_incident', '¿Incidente?', ['si → incident_management', 'no → closeout']),
  task('task_incident_management', 'Gestión Incidente', 'PROJECT_MANAGER'),
  task('task_closeout', 'Cierre', 'AGENCY_OWNER'),
  endEvent('end_closed', 'Proyecto cerrado'),
  endEvent('end_not_fit', 'Lead no apto'),
  endEvent('end_rejected', 'Propuesta rechazada'),
];

const flows = [
  flow('start_lead', 'task_lead_intake'),
  flow('task_lead_intake', 'gw_lead_valid'),
  flow('gw_lead_valid', 'task_qualification', 'si'),
  flow('gw_lead_valid', 'end_not_fit', 'no'),
  flow('task_qualification', 'gw_qualified'),
  flow('gw_qualified', 'task_discovery', 'QUALIFIED/HUMAN_REVIEW'),
  flow('gw_qualified', 'end_not_fit', 'NOT_A_FIT'),
  flow('task_discovery', 'task_diagnosis'),
  flow('task_diagnosis', 'task_requirements'),
  flow('task_requirements', 'task_commercial'),
  flow('task_commercial', 'gw_proposal'),
  flow('gw_proposal', 'task_scope', 'si'),
  flow('gw_proposal', 'end_rejected', 'no'),
  flow('gw_proposal', 'task_commercial', 'revisar'),
  flow('task_scope', 'task_approval'),
  flow('task_approval', 'gw_approved'),
  flow('gw_approved', 'task_production', 'si'),
  flow('gw_approved', 'end_rejected', 'no'),
  flow('task_production', 'task_qa'),
  flow('task_qa', 'gw_qa_pass'),
  flow('gw_qa_pass', 'task_security', 'si'),
  flow('gw_qa_pass', 'task_production', 'no'),
  flow('task_security', 'gw_security_pass'),
  flow('gw_security_pass', 'task_delivery', 'si'),
  flow('gw_security_pass', 'task_production', 'no'),
  flow('task_delivery', 'gw_client_accepts'),
  flow('gw_client_accepts', 'task_handoff', 'si'),
  flow('gw_client_accepts', 'task_change_request', 'no'),
  flow('task_change_request', 'task_delivery'),
  flow('task_handoff', 'task_support'),
  flow('task_support', 'gw_incident'),
  flow('gw_incident', 'task_incident_management', 'si'),
  flow('gw_incident', 'task_closeout', 'no'),
  flow('task_incident_management', 'task_closeout'),
  flow('task_closeout', 'end_closed'),
];

const result = createBPMNProcess({
  id:          'BPMN_AGENCY_MAIN',
  name:        'Agency Full Pipeline',
  description: 'Lead → Qualification → Delivery → Closeout',
  sopRef:      'AGENCY_SOP_FULL_PIPELINE',
  pools: [{
    id:       'pool_agency',
    name:     'Agencia IA',
    lanes: [
      { id: 'lane_commercial',       name: 'Commercial',        owner: 'COMMERCIAL',       elementRefs: ['task_lead_intake', 'task_qualification', 'task_commercial'] },
      { id: 'lane_pm',               name: 'Project Manager',   owner: 'PROJECT_MANAGER',  elementRefs: ['task_discovery', 'task_requirements', 'task_scope', 'task_delivery', 'task_handoff', 'task_change_request', 'task_closeout'] },
      { id: 'lane_ai',               name: 'AI Specialist',     owner: 'AI_SPECIALIST',    elementRefs: ['task_diagnosis'] },
      { id: 'lane_dev',              name: 'Developer',         owner: 'DEVELOPER',        elementRefs: ['task_production'] },
      { id: 'lane_qa',               name: 'QA',                owner: 'QA',               elementRefs: ['task_qa', 'task_security'] },
      { id: 'lane_support',          name: 'Support',           owner: 'SUPPORT',          elementRefs: ['task_support'] },
      { id: 'lane_agency_owner',     name: 'Agency Owner',      owner: 'AGENCY_OWNER',     elementRefs: ['task_approval', 'task_incident_management'] },
    ],
    elements,
  }],
  sequenceFlows: flows,
  version: '1.0.0',
});

export const bpmnAgencyProcess = result.process;
export const BPMN_AGENCY_VERSION = '1.0.0';
