// BPMN Factory — FASE 21: flujo de generación de producto en la fábrica

import {
  createBPMNProcess, startEvent, endEvent, task, serviceTask,
  xorGateway, parallelGateway, flow,
} from './bpmnEngine.js';

const elements = [
  startEvent('start_brief', 'Brief recibido'),
  task('task_analyze_brief', 'Analizar brief', 'DEVELOPER'),
  xorGateway('gw_brief_valid', '¿Brief válido?', ['si → vertical', 'no → request_clarification']),
  task('task_request_clarification', 'Solicitar aclaración', 'PROJECT_MANAGER'),
  task('task_vertical', 'Resolver vertical', 'DEVELOPER'),
  task('task_branding', 'Aplicar branding tokens', 'DEVELOPER'),
  task('task_experience', 'Seleccionar preset de experiencia', 'AI_SPECIALIST'),
  task('task_modules', 'Planificar módulos', 'DEVELOPER'),
  task('task_roles', 'Definir roles', 'DEVELOPER'),
  task('task_data_model', 'Modelo de datos', 'DEVELOPER'),
  parallelGateway('pgw_ai_make_split', 'IA + Make planning'),
  task('task_ai_planning', 'Planificar IA (si aplica)', 'AI_SPECIALIST'),
  task('task_make_planning', 'Planificar automatizaciones (si aplica)', 'AUTOMATION_SPECIALIST'),
  parallelGateway('pgw_ai_make_join', 'Join IA + Make'),
  serviceTask('task_generate', 'Generar producto', 'DEVELOPER'),
  task('task_qa_functional', 'QA Funcional', 'QA'),
  xorGateway('gw_functional_qa', '¿Funcional OK?', ['si → dead_control', 'no → generate']),
  task('task_qa_dead_control', 'QA Dead Controls', 'QA'),
  task('task_qa_mobile', 'QA Mobile', 'QA'),
  task('task_build', 'Build', 'DEVELOPER'),
  xorGateway('gw_build_pass', '¿Build OK?', ['si → security', 'no → generate']),
  task('task_security_review', 'Security Review', 'QA'),
  xorGateway('gw_security_ok', '¿Security OK?', ['si → artifacts', 'no → generate']),
  xorGateway('gw_human_review', '¿Human review requerido?', ['si → human_review_task', 'no → artifacts']),
  task('task_human_review', 'Human Review', 'AGENCY_OWNER'),
  task('task_artifacts', 'Generar artefactos entrega', 'DEVELOPER'),
  endEvent('end_factory_done', 'Producto listo'),
];

const flows = [
  flow('start_brief', 'task_analyze_brief'),
  flow('task_analyze_brief', 'gw_brief_valid'),
  flow('gw_brief_valid', 'task_vertical', 'si'),
  flow('gw_brief_valid', 'task_request_clarification', 'no'),
  flow('task_request_clarification', 'task_analyze_brief'),
  flow('task_vertical', 'task_branding'),
  flow('task_branding', 'task_experience'),
  flow('task_experience', 'task_modules'),
  flow('task_modules', 'task_roles'),
  flow('task_roles', 'task_data_model'),
  flow('task_data_model', 'pgw_ai_make_split'),
  flow('pgw_ai_make_split', 'task_ai_planning'),
  flow('pgw_ai_make_split', 'task_make_planning'),
  flow('task_ai_planning', 'pgw_ai_make_join'),
  flow('task_make_planning', 'pgw_ai_make_join'),
  flow('pgw_ai_make_join', 'task_generate'),
  flow('task_generate', 'task_qa_functional'),
  flow('task_qa_functional', 'gw_functional_qa'),
  flow('gw_functional_qa', 'task_qa_dead_control', 'si'),
  flow('gw_functional_qa', 'task_generate', 'no'),
  flow('task_qa_dead_control', 'task_qa_mobile'),
  flow('task_qa_mobile', 'task_build'),
  flow('task_build', 'gw_build_pass'),
  flow('gw_build_pass', 'task_security_review', 'si'),
  flow('gw_build_pass', 'task_generate', 'no'),
  flow('task_security_review', 'gw_security_ok'),
  flow('gw_security_ok', 'gw_human_review', 'si'),
  flow('gw_security_ok', 'task_generate', 'no'),
  flow('gw_human_review', 'task_human_review', 'si'),
  flow('gw_human_review', 'task_artifacts', 'no'),
  flow('task_human_review', 'task_artifacts'),
  flow('task_artifacts', 'end_factory_done'),
];

const result = createBPMNProcess({
  id:          'BPMN_FACTORY',
  name:        'Factory Product Generation',
  description: 'Brief → Analyze → Generate → QA → Security → Artifacts',
  sopRef:      'FACTORY_PRODUCT_GENERATION',
  pools: [{
    id:   'pool_factory',
    name: 'Factory',
    lanes: [
      { id: 'lane_business_analyzer', name: 'Business Analyzer', owner: 'DEVELOPER',
        elementRefs: ['task_analyze_brief', 'task_vertical', 'task_branding', 'task_modules', 'task_roles', 'task_data_model'] },
      { id: 'lane_factory_gen', name: 'Factory', owner: 'DEVELOPER',
        elementRefs: ['task_generate', 'task_build', 'task_artifacts'] },
      { id: 'lane_ai_router', name: 'AI Router', owner: 'AI_SPECIALIST',
        elementRefs: ['task_experience', 'task_ai_planning'] },
      { id: 'lane_automation_f', name: 'Automation', owner: 'AUTOMATION_SPECIALIST',
        elementRefs: ['task_make_planning'] },
      { id: 'lane_qa_f', name: 'QA', owner: 'QA',
        elementRefs: ['task_qa_functional', 'task_qa_dead_control', 'task_qa_mobile', 'task_security_review'] },
      { id: 'lane_human_review_f', name: 'Human Review', owner: 'AGENCY_OWNER',
        elementRefs: ['task_human_review'] },
    ],
    elements,
  }],
  sequenceFlows: flows,
  version: '1.0.0',
});

export const bpmnFactoryProcess = result.process;
export const BPMN_FACTORY_VERSION = '1.0.0';
